// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/PokemonData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ItemId);
GPB_ENUM_FWD_DECLARE(PokemonId);
GPB_ENUM_FWD_DECLARE(PokemonMove);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PokemonDataRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface PokemonDataRoot : GPBRootObject
@end

#pragma mark - PokemonData

typedef GPB_ENUM(PokemonData_FieldNumber) {
  PokemonData_FieldNumber_Id_p = 1,
  PokemonData_FieldNumber_PokemonId = 2,
  PokemonData_FieldNumber_Cp = 3,
  PokemonData_FieldNumber_Stamina = 4,
  PokemonData_FieldNumber_StaminaMax = 5,
  PokemonData_FieldNumber_Move1 = 6,
  PokemonData_FieldNumber_Move2 = 7,
  PokemonData_FieldNumber_DeployedFortId = 8,
  PokemonData_FieldNumber_OwnerName = 9,
  PokemonData_FieldNumber_IsEgg = 10,
  PokemonData_FieldNumber_EggKmWalkedTarget = 11,
  PokemonData_FieldNumber_EggKmWalkedStart = 12,
  PokemonData_FieldNumber_Origin = 14,
  PokemonData_FieldNumber_HeightM = 15,
  PokemonData_FieldNumber_WeightKg = 16,
  PokemonData_FieldNumber_IndividualAttack = 17,
  PokemonData_FieldNumber_IndividualDefense = 18,
  PokemonData_FieldNumber_IndividualStamina = 19,
  PokemonData_FieldNumber_CpMultiplier = 20,
  PokemonData_FieldNumber_Pokeball = 21,
  PokemonData_FieldNumber_CapturedCellId = 22,
  PokemonData_FieldNumber_BattlesAttacked = 23,
  PokemonData_FieldNumber_BattlesDefended = 24,
  PokemonData_FieldNumber_EggIncubatorId = 25,
  PokemonData_FieldNumber_CreationTimeMs = 26,
  PokemonData_FieldNumber_NumUpgrades = 27,
  PokemonData_FieldNumber_AdditionalCpMultiplier = 28,
  PokemonData_FieldNumber_Favorite = 29,
  PokemonData_FieldNumber_Nickname = 30,
  PokemonData_FieldNumber_FromFort = 31,
};

@interface PokemonData : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite) enum PokemonId pokemonId;

@property(nonatomic, readwrite) int32_t cp;

@property(nonatomic, readwrite) int32_t stamina;

@property(nonatomic, readwrite) int32_t staminaMax;

@property(nonatomic, readwrite) enum PokemonMove move1;

@property(nonatomic, readwrite) enum PokemonMove move2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deployedFortId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerName;

@property(nonatomic, readwrite) BOOL isEgg;

@property(nonatomic, readwrite) double eggKmWalkedTarget;

@property(nonatomic, readwrite) double eggKmWalkedStart;

@property(nonatomic, readwrite) int32_t origin;

@property(nonatomic, readwrite) float heightM;

@property(nonatomic, readwrite) float weightKg;

@property(nonatomic, readwrite) int32_t individualAttack;

@property(nonatomic, readwrite) int32_t individualDefense;

@property(nonatomic, readwrite) int32_t individualStamina;

@property(nonatomic, readwrite) float cpMultiplier;

@property(nonatomic, readwrite) enum ItemId pokeball;

@property(nonatomic, readwrite) uint64_t capturedCellId;

@property(nonatomic, readwrite) int32_t battlesAttacked;

@property(nonatomic, readwrite) int32_t battlesDefended;

@property(nonatomic, readwrite, copy, null_resettable) NSString *eggIncubatorId;

@property(nonatomic, readwrite) uint64_t creationTimeMs;

@property(nonatomic, readwrite) int32_t numUpgrades;

@property(nonatomic, readwrite) float additionalCpMultiplier;

@property(nonatomic, readwrite) int32_t favorite;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@property(nonatomic, readwrite) int32_t fromFort;

@end

/// Fetches the raw value of a @c PokemonData's @c pokemonId property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t PokemonData_PokemonId_RawValue(PokemonData *message);
/// Sets the raw value of an @c PokemonData's @c pokemonId property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPokemonData_PokemonId_RawValue(PokemonData *message, int32_t value);

/// Fetches the raw value of a @c PokemonData's @c move1 property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t PokemonData_Move1_RawValue(PokemonData *message);
/// Sets the raw value of an @c PokemonData's @c move1 property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPokemonData_Move1_RawValue(PokemonData *message, int32_t value);

/// Fetches the raw value of a @c PokemonData's @c move2 property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t PokemonData_Move2_RawValue(PokemonData *message);
/// Sets the raw value of an @c PokemonData's @c move2 property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPokemonData_Move2_RawValue(PokemonData *message, int32_t value);

/// Fetches the raw value of a @c PokemonData's @c pokeball property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t PokemonData_Pokeball_RawValue(PokemonData *message);
/// Sets the raw value of an @c PokemonData's @c pokeball property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPokemonData_Pokeball_RawValue(PokemonData *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
