// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/Pokemon/NearbyPokemon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "NearbyPokemon.pbobjc.h"
 #import "PokemonId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NearbyPokemonRoot

@implementation NearbyPokemonRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PokemonIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - NearbyPokemonRoot_FileDescriptor

static GPBFileDescriptor *NearbyPokemonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Map.Pokemon"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - NearbyPokemon

@implementation NearbyPokemon

@dynamic pokemonId;
@dynamic distanceInMeters;
@dynamic encounterId;

typedef struct NearbyPokemon__storage_ {
  uint32_t _has_storage_[1];
  PokemonId pokemonId;
  float distanceInMeters;
  uint64_t encounterId;
} NearbyPokemon__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pokemonId",
        .dataTypeSpecific.enumDescFunc = PokemonId_EnumDescriptor,
        .number = NearbyPokemon_FieldNumber_PokemonId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NearbyPokemon__storage_, pokemonId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "distanceInMeters",
        .dataTypeSpecific.className = NULL,
        .number = NearbyPokemon_FieldNumber_DistanceInMeters,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NearbyPokemon__storage_, distanceInMeters),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = NearbyPokemon_FieldNumber_EncounterId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(NearbyPokemon__storage_, encounterId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NearbyPokemon class]
                                     rootClass:[NearbyPokemonRoot class]
                                          file:NearbyPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NearbyPokemon__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t NearbyPokemon_PokemonId_RawValue(NearbyPokemon *message) {
  GPBDescriptor *descriptor = [NearbyPokemon descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NearbyPokemon_FieldNumber_PokemonId];
  return GPBGetMessageInt32Field(message, field);
}

void SetNearbyPokemon_PokemonId_RawValue(NearbyPokemon *message, int32_t value) {
  GPBDescriptor *descriptor = [NearbyPokemon descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NearbyPokemon_FieldNumber_PokemonId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
