// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Pokemon/StatsAttributes.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - StatsAttributesRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface StatsAttributesRoot : GPBRootObject
@end

#pragma mark - StatsAttributes

typedef GPB_ENUM(StatsAttributes_FieldNumber) {
  StatsAttributes_FieldNumber_BaseStamina = 1,
  StatsAttributes_FieldNumber_BaseAttack = 2,
  StatsAttributes_FieldNumber_BaseDefense = 3,
  StatsAttributes_FieldNumber_DodgeEnergyDelta = 8,
};

@interface StatsAttributes : GPBMessage

@property(nonatomic, readwrite) int32_t baseStamina;

@property(nonatomic, readwrite) int32_t baseAttack;

@property(nonatomic, readwrite) int32_t baseDefense;

@property(nonatomic, readwrite) int32_t dodgeEnergyDelta;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
