// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/GymLevelSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GymLevelSettings.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GymLevelSettingsRoot

@implementation GymLevelSettingsRoot

@end

#pragma mark - GymLevelSettingsRoot_FileDescriptor

static GPBFileDescriptor *GymLevelSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings.Master"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GymLevelSettings

@implementation GymLevelSettings

@dynamic requiredExperienceArray, requiredExperienceArray_Count;
@dynamic leaderSlotsArray, leaderSlotsArray_Count;
@dynamic trainerSlotsArray, trainerSlotsArray_Count;
@dynamic searchRollBonusArray, searchRollBonusArray_Count;

typedef struct GymLevelSettings__storage_ {
  uint32_t _has_storage_[1];
  GPBInt32Array *requiredExperienceArray;
  GPBInt32Array *leaderSlotsArray;
  GPBInt32Array *trainerSlotsArray;
  GPBInt32Array *searchRollBonusArray;
} GymLevelSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requiredExperienceArray",
        .dataTypeSpecific.className = NULL,
        .number = GymLevelSettings_FieldNumber_RequiredExperienceArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GymLevelSettings__storage_, requiredExperienceArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "leaderSlotsArray",
        .dataTypeSpecific.className = NULL,
        .number = GymLevelSettings_FieldNumber_LeaderSlotsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GymLevelSettings__storage_, leaderSlotsArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "trainerSlotsArray",
        .dataTypeSpecific.className = NULL,
        .number = GymLevelSettings_FieldNumber_TrainerSlotsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GymLevelSettings__storage_, trainerSlotsArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "searchRollBonusArray",
        .dataTypeSpecific.className = NULL,
        .number = GymLevelSettings_FieldNumber_SearchRollBonusArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GymLevelSettings__storage_, searchRollBonusArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GymLevelSettings class]
                                     rootClass:[GymLevelSettingsRoot class]
                                          file:GymLevelSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GymLevelSettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
