// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/TypeEffectiveSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "TypeEffectiveSettings.pbobjc.h"
 #import "PokemonType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TypeEffectiveSettingsRoot

@implementation TypeEffectiveSettingsRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PokemonTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - TypeEffectiveSettingsRoot_FileDescriptor

static GPBFileDescriptor *TypeEffectiveSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings.Master"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - TypeEffectiveSettings

@implementation TypeEffectiveSettings

@dynamic attackScalarArray, attackScalarArray_Count;
@dynamic attackType;

typedef struct TypeEffectiveSettings__storage_ {
  uint32_t _has_storage_[1];
  PokemonType attackType;
  GPBFloatArray *attackScalarArray;
} TypeEffectiveSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "attackScalarArray",
        .dataTypeSpecific.className = NULL,
        .number = TypeEffectiveSettings_FieldNumber_AttackScalarArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TypeEffectiveSettings__storage_, attackScalarArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "attackType",
        .dataTypeSpecific.enumDescFunc = PokemonType_EnumDescriptor,
        .number = TypeEffectiveSettings_FieldNumber_AttackType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TypeEffectiveSettings__storage_, attackType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TypeEffectiveSettings class]
                                     rootClass:[TypeEffectiveSettingsRoot class]
                                          file:TypeEffectiveSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TypeEffectiveSettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t TypeEffectiveSettings_AttackType_RawValue(TypeEffectiveSettings *message) {
  GPBDescriptor *descriptor = [TypeEffectiveSettings descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:TypeEffectiveSettings_FieldNumber_AttackType];
  return GPBGetMessageInt32Field(message, field);
}

void SetTypeEffectiveSettings_AttackType_RawValue(TypeEffectiveSettings *message, int32_t value) {
  GPBDescriptor *descriptor = [TypeEffectiveSettings descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:TypeEffectiveSettings_FieldNumber_AttackType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
