// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/CameraInterpolation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "CameraInterpolation.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CameraInterpolationRoot

@implementation CameraInterpolationRoot

@end

#pragma mark - Enum CameraInterpolation

GPBEnumDescriptor *CameraInterpolation_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "CamInterpCut\000CamInterpLinear\000CamInterpSm"
        "ooth\000CamInterpSmoothRotLinearMove\000CamInt"
        "erpDepends\000";
    static const int32_t values[] = {
        CameraInterpolation_CamInterpCut,
        CameraInterpolation_CamInterpLinear,
        CameraInterpolation_CamInterpSmooth,
        CameraInterpolation_CamInterpSmoothRotLinearMove,
        CameraInterpolation_CamInterpDepends,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CameraInterpolation)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CameraInterpolation_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL CameraInterpolation_IsValidValue(int32_t value__) {
  switch (value__) {
    case CameraInterpolation_CamInterpCut:
    case CameraInterpolation_CamInterpLinear:
    case CameraInterpolation_CamInterpSmooth:
    case CameraInterpolation_CamInterpSmoothRotLinearMove:
    case CameraInterpolation_CamInterpDepends:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
