// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonFamilyId.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PokemonFamilyId

typedef GPB_ENUM(PokemonFamilyId) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  PokemonFamilyId_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PokemonFamilyId_FamilyUnset = 0,
  PokemonFamilyId_FamilyBulbasaur = 1,
  PokemonFamilyId_FamilyCharmander = 4,
  PokemonFamilyId_FamilySquirtle = 7,
  PokemonFamilyId_FamilyCaterpie = 10,
  PokemonFamilyId_FamilyWeedle = 13,
  PokemonFamilyId_FamilyPidgey = 16,
  PokemonFamilyId_FamilyRattata = 19,
  PokemonFamilyId_FamilySpearow = 21,
  PokemonFamilyId_FamilyEkans = 23,
  PokemonFamilyId_FamilyPikachu = 25,
  PokemonFamilyId_FamilySandshrew = 27,
  PokemonFamilyId_FamilyNidoranFemale = 29,
  PokemonFamilyId_FamilyNidoranMale = 32,
  PokemonFamilyId_FamilyClefairy = 35,
  PokemonFamilyId_FamilyVulpix = 37,
  PokemonFamilyId_FamilyJigglypuff = 39,
  PokemonFamilyId_FamilyZubat = 41,
  PokemonFamilyId_FamilyOddish = 43,
  PokemonFamilyId_FamilyParas = 46,
  PokemonFamilyId_FamilyVenonat = 48,
  PokemonFamilyId_FamilyDiglett = 50,
  PokemonFamilyId_FamilyMeowth = 52,
  PokemonFamilyId_FamilyPsyduck = 54,
  PokemonFamilyId_FamilyMankey = 56,
  PokemonFamilyId_FamilyGrowlithe = 58,
  PokemonFamilyId_FamilyPoliwag = 60,
  PokemonFamilyId_FamilyAbra = 63,
  PokemonFamilyId_FamilyMachop = 66,
  PokemonFamilyId_FamilyBellsprout = 69,
  PokemonFamilyId_FamilyTentacool = 72,
  PokemonFamilyId_FamilyGeodude = 74,
  PokemonFamilyId_FamilyPonyta = 77,
  PokemonFamilyId_FamilySlowpoke = 79,
  PokemonFamilyId_FamilyMagnemite = 81,
  PokemonFamilyId_FamilyFarfetchd = 83,
  PokemonFamilyId_FamilyDoduo = 84,
  PokemonFamilyId_FamilySeel = 86,
  PokemonFamilyId_FamilyGrimer = 88,
  PokemonFamilyId_FamilyShellder = 90,
  PokemonFamilyId_FamilyGastly = 92,
  PokemonFamilyId_FamilyOnix = 95,
  PokemonFamilyId_FamilyDrowzee = 96,
  PokemonFamilyId_FamilyHypno = 97,
  PokemonFamilyId_FamilyKrabby = 98,
  PokemonFamilyId_FamilyVoltorb = 100,
  PokemonFamilyId_FamilyExeggcute = 102,
  PokemonFamilyId_FamilyCubone = 104,
  PokemonFamilyId_FamilyHitmonlee = 106,
  PokemonFamilyId_FamilyHitmonchan = 107,
  PokemonFamilyId_FamilyLickitung = 108,
  PokemonFamilyId_FamilyKoffing = 109,
  PokemonFamilyId_FamilyRhyhorn = 111,
  PokemonFamilyId_FamilyChansey = 113,
  PokemonFamilyId_FamilyTangela = 114,
  PokemonFamilyId_FamilyKangaskhan = 115,
  PokemonFamilyId_FamilyHorsea = 116,
  PokemonFamilyId_FamilyGoldeen = 118,
  PokemonFamilyId_FamilyStaryu = 120,
  PokemonFamilyId_FamilyMrMime = 122,
  PokemonFamilyId_FamilyScyther = 123,
  PokemonFamilyId_FamilyJynx = 124,
  PokemonFamilyId_FamilyElectabuzz = 125,
  PokemonFamilyId_FamilyMagmar = 126,
  PokemonFamilyId_FamilyPinsir = 127,
  PokemonFamilyId_FamilyTauros = 128,
  PokemonFamilyId_FamilyMagikarp = 129,
  PokemonFamilyId_FamilyLapras = 131,
  PokemonFamilyId_FamilyDitto = 132,
  PokemonFamilyId_FamilyEevee = 133,
  PokemonFamilyId_FamilyPorygon = 137,
  PokemonFamilyId_FamilyOmanyte = 138,
  PokemonFamilyId_FamilyKabuto = 140,
  PokemonFamilyId_FamilyAerodactyl = 142,
  PokemonFamilyId_FamilySnorlax = 143,
  PokemonFamilyId_FamilyArticuno = 144,
  PokemonFamilyId_FamilyZapdos = 145,
  PokemonFamilyId_FamilyMoltres = 146,
  PokemonFamilyId_FamilyDratini = 147,
  PokemonFamilyId_FamilyMewtwo = 150,
  PokemonFamilyId_FamilyMew = 151,
};

GPBEnumDescriptor *PokemonFamilyId_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL PokemonFamilyId_IsValidValue(int32_t value);

#pragma mark - PokemonFamilyIdRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface PokemonFamilyIdRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
