// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PokemonType

typedef GPB_ENUM(PokemonType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  PokemonType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PokemonType_PokemonTypeNone = 0,
  PokemonType_PokemonTypeNormal = 1,
  PokemonType_PokemonTypeFighting = 2,
  PokemonType_PokemonTypeFlying = 3,
  PokemonType_PokemonTypePoison = 4,
  PokemonType_PokemonTypeGround = 5,
  PokemonType_PokemonTypeRock = 6,
  PokemonType_PokemonTypeBug = 7,
  PokemonType_PokemonTypeGhost = 8,
  PokemonType_PokemonTypeSteel = 9,
  PokemonType_PokemonTypeFire = 10,
  PokemonType_PokemonTypeWater = 11,
  PokemonType_PokemonTypeGrass = 12,
  PokemonType_PokemonTypeElectric = 13,
  PokemonType_PokemonTypePsychic = 14,
  PokemonType_PokemonTypeIce = 15,
  PokemonType_PokemonTypeDragon = 16,
  PokemonType_PokemonTypeDark = 17,
  PokemonType_PokemonTypeFairy = 18,
};

GPBEnumDescriptor *PokemonType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL PokemonType_IsValidValue(int32_t value);

#pragma mark - PokemonTypeRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface PokemonTypeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
