// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonFamilyId.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "PokemonFamilyId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PokemonFamilyIdRoot

@implementation PokemonFamilyIdRoot

@end

#pragma mark - Enum PokemonFamilyId

GPBEnumDescriptor *PokemonFamilyId_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "FamilyUnset\000FamilyBulbasaur\000FamilyCharma"
        "nder\000FamilySquirtle\000FamilyCaterpie\000Famil"
        "yWeedle\000FamilyPidgey\000FamilyRattata\000Famil"
        "ySpearow\000FamilyEkans\000FamilyPikachu\000Famil"
        "ySandshrew\000FamilyNidoranFemale\000FamilyNid"
        "oranMale\000FamilyClefairy\000FamilyVulpix\000Fam"
        "ilyJigglypuff\000FamilyZubat\000FamilyOddish\000F"
        "amilyParas\000FamilyVenonat\000FamilyDiglett\000F"
        "amilyMeowth\000FamilyPsyduck\000FamilyMankey\000F"
        "amilyGrowlithe\000FamilyPoliwag\000FamilyAbra\000"
        "FamilyMachop\000FamilyBellsprout\000FamilyTent"
        "acool\000FamilyGeodude\000FamilyPonyta\000FamilyS"
        "lowpoke\000FamilyMagnemite\000FamilyFarfetchd\000"
        "FamilyDoduo\000FamilySeel\000FamilyGrimer\000Fami"
        "lyShellder\000FamilyGastly\000FamilyOnix\000Famil"
        "yDrowzee\000FamilyHypno\000FamilyKrabby\000Family"
        "Voltorb\000FamilyExeggcute\000FamilyCubone\000Fam"
        "ilyHitmonlee\000FamilyHitmonchan\000FamilyLick"
        "itung\000FamilyKoffing\000FamilyRhyhorn\000Family"
        "Chansey\000FamilyTangela\000FamilyKangaskhan\000F"
        "amilyHorsea\000FamilyGoldeen\000FamilyStaryu\000F"
        "amilyMrMime\000FamilyScyther\000FamilyJynx\000Fam"
        "ilyElectabuzz\000FamilyMagmar\000FamilyPinsir\000"
        "FamilyTauros\000FamilyMagikarp\000FamilyLapras"
        "\000FamilyDitto\000FamilyEevee\000FamilyPorygon\000F"
        "amilyOmanyte\000FamilyKabuto\000FamilyAerodact"
        "yl\000FamilySnorlax\000FamilyArticuno\000FamilyZa"
        "pdos\000FamilyMoltres\000FamilyDratini\000FamilyM"
        "ewtwo\000FamilyMew\000";
    static const int32_t values[] = {
        PokemonFamilyId_FamilyUnset,
        PokemonFamilyId_FamilyBulbasaur,
        PokemonFamilyId_FamilyCharmander,
        PokemonFamilyId_FamilySquirtle,
        PokemonFamilyId_FamilyCaterpie,
        PokemonFamilyId_FamilyWeedle,
        PokemonFamilyId_FamilyPidgey,
        PokemonFamilyId_FamilyRattata,
        PokemonFamilyId_FamilySpearow,
        PokemonFamilyId_FamilyEkans,
        PokemonFamilyId_FamilyPikachu,
        PokemonFamilyId_FamilySandshrew,
        PokemonFamilyId_FamilyNidoranFemale,
        PokemonFamilyId_FamilyNidoranMale,
        PokemonFamilyId_FamilyClefairy,
        PokemonFamilyId_FamilyVulpix,
        PokemonFamilyId_FamilyJigglypuff,
        PokemonFamilyId_FamilyZubat,
        PokemonFamilyId_FamilyOddish,
        PokemonFamilyId_FamilyParas,
        PokemonFamilyId_FamilyVenonat,
        PokemonFamilyId_FamilyDiglett,
        PokemonFamilyId_FamilyMeowth,
        PokemonFamilyId_FamilyPsyduck,
        PokemonFamilyId_FamilyMankey,
        PokemonFamilyId_FamilyGrowlithe,
        PokemonFamilyId_FamilyPoliwag,
        PokemonFamilyId_FamilyAbra,
        PokemonFamilyId_FamilyMachop,
        PokemonFamilyId_FamilyBellsprout,
        PokemonFamilyId_FamilyTentacool,
        PokemonFamilyId_FamilyGeodude,
        PokemonFamilyId_FamilyPonyta,
        PokemonFamilyId_FamilySlowpoke,
        PokemonFamilyId_FamilyMagnemite,
        PokemonFamilyId_FamilyFarfetchd,
        PokemonFamilyId_FamilyDoduo,
        PokemonFamilyId_FamilySeel,
        PokemonFamilyId_FamilyGrimer,
        PokemonFamilyId_FamilyShellder,
        PokemonFamilyId_FamilyGastly,
        PokemonFamilyId_FamilyOnix,
        PokemonFamilyId_FamilyDrowzee,
        PokemonFamilyId_FamilyHypno,
        PokemonFamilyId_FamilyKrabby,
        PokemonFamilyId_FamilyVoltorb,
        PokemonFamilyId_FamilyExeggcute,
        PokemonFamilyId_FamilyCubone,
        PokemonFamilyId_FamilyHitmonlee,
        PokemonFamilyId_FamilyHitmonchan,
        PokemonFamilyId_FamilyLickitung,
        PokemonFamilyId_FamilyKoffing,
        PokemonFamilyId_FamilyRhyhorn,
        PokemonFamilyId_FamilyChansey,
        PokemonFamilyId_FamilyTangela,
        PokemonFamilyId_FamilyKangaskhan,
        PokemonFamilyId_FamilyHorsea,
        PokemonFamilyId_FamilyGoldeen,
        PokemonFamilyId_FamilyStaryu,
        PokemonFamilyId_FamilyMrMime,
        PokemonFamilyId_FamilyScyther,
        PokemonFamilyId_FamilyJynx,
        PokemonFamilyId_FamilyElectabuzz,
        PokemonFamilyId_FamilyMagmar,
        PokemonFamilyId_FamilyPinsir,
        PokemonFamilyId_FamilyTauros,
        PokemonFamilyId_FamilyMagikarp,
        PokemonFamilyId_FamilyLapras,
        PokemonFamilyId_FamilyDitto,
        PokemonFamilyId_FamilyEevee,
        PokemonFamilyId_FamilyPorygon,
        PokemonFamilyId_FamilyOmanyte,
        PokemonFamilyId_FamilyKabuto,
        PokemonFamilyId_FamilyAerodactyl,
        PokemonFamilyId_FamilySnorlax,
        PokemonFamilyId_FamilyArticuno,
        PokemonFamilyId_FamilyZapdos,
        PokemonFamilyId_FamilyMoltres,
        PokemonFamilyId_FamilyDratini,
        PokemonFamilyId_FamilyMewtwo,
        PokemonFamilyId_FamilyMew,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(PokemonFamilyId)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:PokemonFamilyId_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL PokemonFamilyId_IsValidValue(int32_t value__) {
  switch (value__) {
    case PokemonFamilyId_FamilyUnset:
    case PokemonFamilyId_FamilyBulbasaur:
    case PokemonFamilyId_FamilyCharmander:
    case PokemonFamilyId_FamilySquirtle:
    case PokemonFamilyId_FamilyCaterpie:
    case PokemonFamilyId_FamilyWeedle:
    case PokemonFamilyId_FamilyPidgey:
    case PokemonFamilyId_FamilyRattata:
    case PokemonFamilyId_FamilySpearow:
    case PokemonFamilyId_FamilyEkans:
    case PokemonFamilyId_FamilyPikachu:
    case PokemonFamilyId_FamilySandshrew:
    case PokemonFamilyId_FamilyNidoranFemale:
    case PokemonFamilyId_FamilyNidoranMale:
    case PokemonFamilyId_FamilyClefairy:
    case PokemonFamilyId_FamilyVulpix:
    case PokemonFamilyId_FamilyJigglypuff:
    case PokemonFamilyId_FamilyZubat:
    case PokemonFamilyId_FamilyOddish:
    case PokemonFamilyId_FamilyParas:
    case PokemonFamilyId_FamilyVenonat:
    case PokemonFamilyId_FamilyDiglett:
    case PokemonFamilyId_FamilyMeowth:
    case PokemonFamilyId_FamilyPsyduck:
    case PokemonFamilyId_FamilyMankey:
    case PokemonFamilyId_FamilyGrowlithe:
    case PokemonFamilyId_FamilyPoliwag:
    case PokemonFamilyId_FamilyAbra:
    case PokemonFamilyId_FamilyMachop:
    case PokemonFamilyId_FamilyBellsprout:
    case PokemonFamilyId_FamilyTentacool:
    case PokemonFamilyId_FamilyGeodude:
    case PokemonFamilyId_FamilyPonyta:
    case PokemonFamilyId_FamilySlowpoke:
    case PokemonFamilyId_FamilyMagnemite:
    case PokemonFamilyId_FamilyFarfetchd:
    case PokemonFamilyId_FamilyDoduo:
    case PokemonFamilyId_FamilySeel:
    case PokemonFamilyId_FamilyGrimer:
    case PokemonFamilyId_FamilyShellder:
    case PokemonFamilyId_FamilyGastly:
    case PokemonFamilyId_FamilyOnix:
    case PokemonFamilyId_FamilyDrowzee:
    case PokemonFamilyId_FamilyHypno:
    case PokemonFamilyId_FamilyKrabby:
    case PokemonFamilyId_FamilyVoltorb:
    case PokemonFamilyId_FamilyExeggcute:
    case PokemonFamilyId_FamilyCubone:
    case PokemonFamilyId_FamilyHitmonlee:
    case PokemonFamilyId_FamilyHitmonchan:
    case PokemonFamilyId_FamilyLickitung:
    case PokemonFamilyId_FamilyKoffing:
    case PokemonFamilyId_FamilyRhyhorn:
    case PokemonFamilyId_FamilyChansey:
    case PokemonFamilyId_FamilyTangela:
    case PokemonFamilyId_FamilyKangaskhan:
    case PokemonFamilyId_FamilyHorsea:
    case PokemonFamilyId_FamilyGoldeen:
    case PokemonFamilyId_FamilyStaryu:
    case PokemonFamilyId_FamilyMrMime:
    case PokemonFamilyId_FamilyScyther:
    case PokemonFamilyId_FamilyJynx:
    case PokemonFamilyId_FamilyElectabuzz:
    case PokemonFamilyId_FamilyMagmar:
    case PokemonFamilyId_FamilyPinsir:
    case PokemonFamilyId_FamilyTauros:
    case PokemonFamilyId_FamilyMagikarp:
    case PokemonFamilyId_FamilyLapras:
    case PokemonFamilyId_FamilyDitto:
    case PokemonFamilyId_FamilyEevee:
    case PokemonFamilyId_FamilyPorygon:
    case PokemonFamilyId_FamilyOmanyte:
    case PokemonFamilyId_FamilyKabuto:
    case PokemonFamilyId_FamilyAerodactyl:
    case PokemonFamilyId_FamilySnorlax:
    case PokemonFamilyId_FamilyArticuno:
    case PokemonFamilyId_FamilyZapdos:
    case PokemonFamilyId_FamilyMoltres:
    case PokemonFamilyId_FamilyDratini:
    case PokemonFamilyId_FamilyMewtwo:
    case PokemonFamilyId_FamilyMew:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
