// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonId.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "PokemonId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PokemonIdRoot

@implementation PokemonIdRoot

@end

#pragma mark - Enum PokemonId

GPBEnumDescriptor *PokemonId_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Missingno\000Bulbasaur\000Ivysaur\000Venusaur\000Cha"
        "rmander\000Charmeleon\000Charizard\000Squirtle\000Wa"
        "rtortle\000Blastoise\000Caterpie\000Metapod\000Butte"
        "rfree\000Weedle\000Kakuna\000Beedrill\000Pidgey\000Pidg"
        "eotto\000Pidgeot\000Rattata\000Raticate\000Spearow\000F"
        "earow\000Ekans\000Arbok\000Pikachu\000Raichu\000Sandshr"
        "ew\000Sandslash\000NidoranFemale\000Nidorina\000Nido"
        "queen\000NidoranMale\000Nidorino\000Nidoking\000Clef"
        "airy\000Clefable\000Vulpix\000Ninetales\000Jigglypuf"
        "f\000Wigglytuff\000Zubat\000Golbat\000Oddish\000Gloom\000V"
        "ileplume\000Paras\000Parasect\000Venonat\000Venomoth"
        "\000Diglett\000Dugtrio\000Meowth\000Persian\000Psyduck\000"
        "Golduck\000Mankey\000Primeape\000Growlithe\000Arcani"
        "ne\000Poliwag\000Poliwhirl\000Poliwrath\000Abra\000Kada"
        "bra\000Alakazam\000Machop\000Machoke\000Machamp\000Bell"
        "sprout\000Weepinbell\000Victreebel\000Tentacool\000T"
        "entacruel\000Geodude\000Graveler\000Golem\000Ponyta\000"
        "Rapidash\000Slowpoke\000Slowbro\000Magnemite\000Magn"
        "eton\000Farfetchd\000Doduo\000Dodrio\000Seel\000Dewgong"
        "\000Grimer\000Muk\000Shellder\000Cloyster\000Gastly\000Hau"
        "nter\000Gengar\000Onix\000Drowzee\000Hypno\000Krabby\000Ki"
        "ngler\000Voltorb\000Electrode\000Exeggcute\000Exeggu"
        "tor\000Cubone\000Marowak\000Hitmonlee\000Hitmonchan\000"
        "Lickitung\000Koffing\000Weezing\000Rhyhorn\000Rhydon"
        "\000Chansey\000Tangela\000Kangaskhan\000Horsea\000Seadr"
        "a\000Goldeen\000Seaking\000Staryu\000Starmie\000MrMime\000"
        "Scyther\000Jynx\000Electabuzz\000Magmar\000Pinsir\000Ta"
        "uros\000Magikarp\000Gyarados\000Lapras\000Ditto\000Eeve"
        "e\000Vaporeon\000Jolteon\000Flareon\000Porygon\000Omany"
        "te\000Omastar\000Kabuto\000Kabutops\000Aerodactyl\000Sn"
        "orlax\000Articuno\000Zapdos\000Moltres\000Dratini\000Dr"
        "agonair\000Dragonite\000Mewtwo\000Mew\000";
    static const int32_t values[] = {
        PokemonId_Missingno,
        PokemonId_Bulbasaur,
        PokemonId_Ivysaur,
        PokemonId_Venusaur,
        PokemonId_Charmander,
        PokemonId_Charmeleon,
        PokemonId_Charizard,
        PokemonId_Squirtle,
        PokemonId_Wartortle,
        PokemonId_Blastoise,
        PokemonId_Caterpie,
        PokemonId_Metapod,
        PokemonId_Butterfree,
        PokemonId_Weedle,
        PokemonId_Kakuna,
        PokemonId_Beedrill,
        PokemonId_Pidgey,
        PokemonId_Pidgeotto,
        PokemonId_Pidgeot,
        PokemonId_Rattata,
        PokemonId_Raticate,
        PokemonId_Spearow,
        PokemonId_Fearow,
        PokemonId_Ekans,
        PokemonId_Arbok,
        PokemonId_Pikachu,
        PokemonId_Raichu,
        PokemonId_Sandshrew,
        PokemonId_Sandslash,
        PokemonId_NidoranFemale,
        PokemonId_Nidorina,
        PokemonId_Nidoqueen,
        PokemonId_NidoranMale,
        PokemonId_Nidorino,
        PokemonId_Nidoking,
        PokemonId_Clefairy,
        PokemonId_Clefable,
        PokemonId_Vulpix,
        PokemonId_Ninetales,
        PokemonId_Jigglypuff,
        PokemonId_Wigglytuff,
        PokemonId_Zubat,
        PokemonId_Golbat,
        PokemonId_Oddish,
        PokemonId_Gloom,
        PokemonId_Vileplume,
        PokemonId_Paras,
        PokemonId_Parasect,
        PokemonId_Venonat,
        PokemonId_Venomoth,
        PokemonId_Diglett,
        PokemonId_Dugtrio,
        PokemonId_Meowth,
        PokemonId_Persian,
        PokemonId_Psyduck,
        PokemonId_Golduck,
        PokemonId_Mankey,
        PokemonId_Primeape,
        PokemonId_Growlithe,
        PokemonId_Arcanine,
        PokemonId_Poliwag,
        PokemonId_Poliwhirl,
        PokemonId_Poliwrath,
        PokemonId_Abra,
        PokemonId_Kadabra,
        PokemonId_Alakazam,
        PokemonId_Machop,
        PokemonId_Machoke,
        PokemonId_Machamp,
        PokemonId_Bellsprout,
        PokemonId_Weepinbell,
        PokemonId_Victreebel,
        PokemonId_Tentacool,
        PokemonId_Tentacruel,
        PokemonId_Geodude,
        PokemonId_Graveler,
        PokemonId_Golem,
        PokemonId_Ponyta,
        PokemonId_Rapidash,
        PokemonId_Slowpoke,
        PokemonId_Slowbro,
        PokemonId_Magnemite,
        PokemonId_Magneton,
        PokemonId_Farfetchd,
        PokemonId_Doduo,
        PokemonId_Dodrio,
        PokemonId_Seel,
        PokemonId_Dewgong,
        PokemonId_Grimer,
        PokemonId_Muk,
        PokemonId_Shellder,
        PokemonId_Cloyster,
        PokemonId_Gastly,
        PokemonId_Haunter,
        PokemonId_Gengar,
        PokemonId_Onix,
        PokemonId_Drowzee,
        PokemonId_Hypno,
        PokemonId_Krabby,
        PokemonId_Kingler,
        PokemonId_Voltorb,
        PokemonId_Electrode,
        PokemonId_Exeggcute,
        PokemonId_Exeggutor,
        PokemonId_Cubone,
        PokemonId_Marowak,
        PokemonId_Hitmonlee,
        PokemonId_Hitmonchan,
        PokemonId_Lickitung,
        PokemonId_Koffing,
        PokemonId_Weezing,
        PokemonId_Rhyhorn,
        PokemonId_Rhydon,
        PokemonId_Chansey,
        PokemonId_Tangela,
        PokemonId_Kangaskhan,
        PokemonId_Horsea,
        PokemonId_Seadra,
        PokemonId_Goldeen,
        PokemonId_Seaking,
        PokemonId_Staryu,
        PokemonId_Starmie,
        PokemonId_MrMime,
        PokemonId_Scyther,
        PokemonId_Jynx,
        PokemonId_Electabuzz,
        PokemonId_Magmar,
        PokemonId_Pinsir,
        PokemonId_Tauros,
        PokemonId_Magikarp,
        PokemonId_Gyarados,
        PokemonId_Lapras,
        PokemonId_Ditto,
        PokemonId_Eevee,
        PokemonId_Vaporeon,
        PokemonId_Jolteon,
        PokemonId_Flareon,
        PokemonId_Porygon,
        PokemonId_Omanyte,
        PokemonId_Omastar,
        PokemonId_Kabuto,
        PokemonId_Kabutops,
        PokemonId_Aerodactyl,
        PokemonId_Snorlax,
        PokemonId_Articuno,
        PokemonId_Zapdos,
        PokemonId_Moltres,
        PokemonId_Dratini,
        PokemonId_Dragonair,
        PokemonId_Dragonite,
        PokemonId_Mewtwo,
        PokemonId_Mew,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(PokemonId)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:PokemonId_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL PokemonId_IsValidValue(int32_t value__) {
  switch (value__) {
    case PokemonId_Missingno:
    case PokemonId_Bulbasaur:
    case PokemonId_Ivysaur:
    case PokemonId_Venusaur:
    case PokemonId_Charmander:
    case PokemonId_Charmeleon:
    case PokemonId_Charizard:
    case PokemonId_Squirtle:
    case PokemonId_Wartortle:
    case PokemonId_Blastoise:
    case PokemonId_Caterpie:
    case PokemonId_Metapod:
    case PokemonId_Butterfree:
    case PokemonId_Weedle:
    case PokemonId_Kakuna:
    case PokemonId_Beedrill:
    case PokemonId_Pidgey:
    case PokemonId_Pidgeotto:
    case PokemonId_Pidgeot:
    case PokemonId_Rattata:
    case PokemonId_Raticate:
    case PokemonId_Spearow:
    case PokemonId_Fearow:
    case PokemonId_Ekans:
    case PokemonId_Arbok:
    case PokemonId_Pikachu:
    case PokemonId_Raichu:
    case PokemonId_Sandshrew:
    case PokemonId_Sandslash:
    case PokemonId_NidoranFemale:
    case PokemonId_Nidorina:
    case PokemonId_Nidoqueen:
    case PokemonId_NidoranMale:
    case PokemonId_Nidorino:
    case PokemonId_Nidoking:
    case PokemonId_Clefairy:
    case PokemonId_Clefable:
    case PokemonId_Vulpix:
    case PokemonId_Ninetales:
    case PokemonId_Jigglypuff:
    case PokemonId_Wigglytuff:
    case PokemonId_Zubat:
    case PokemonId_Golbat:
    case PokemonId_Oddish:
    case PokemonId_Gloom:
    case PokemonId_Vileplume:
    case PokemonId_Paras:
    case PokemonId_Parasect:
    case PokemonId_Venonat:
    case PokemonId_Venomoth:
    case PokemonId_Diglett:
    case PokemonId_Dugtrio:
    case PokemonId_Meowth:
    case PokemonId_Persian:
    case PokemonId_Psyduck:
    case PokemonId_Golduck:
    case PokemonId_Mankey:
    case PokemonId_Primeape:
    case PokemonId_Growlithe:
    case PokemonId_Arcanine:
    case PokemonId_Poliwag:
    case PokemonId_Poliwhirl:
    case PokemonId_Poliwrath:
    case PokemonId_Abra:
    case PokemonId_Kadabra:
    case PokemonId_Alakazam:
    case PokemonId_Machop:
    case PokemonId_Machoke:
    case PokemonId_Machamp:
    case PokemonId_Bellsprout:
    case PokemonId_Weepinbell:
    case PokemonId_Victreebel:
    case PokemonId_Tentacool:
    case PokemonId_Tentacruel:
    case PokemonId_Geodude:
    case PokemonId_Graveler:
    case PokemonId_Golem:
    case PokemonId_Ponyta:
    case PokemonId_Rapidash:
    case PokemonId_Slowpoke:
    case PokemonId_Slowbro:
    case PokemonId_Magnemite:
    case PokemonId_Magneton:
    case PokemonId_Farfetchd:
    case PokemonId_Doduo:
    case PokemonId_Dodrio:
    case PokemonId_Seel:
    case PokemonId_Dewgong:
    case PokemonId_Grimer:
    case PokemonId_Muk:
    case PokemonId_Shellder:
    case PokemonId_Cloyster:
    case PokemonId_Gastly:
    case PokemonId_Haunter:
    case PokemonId_Gengar:
    case PokemonId_Onix:
    case PokemonId_Drowzee:
    case PokemonId_Hypno:
    case PokemonId_Krabby:
    case PokemonId_Kingler:
    case PokemonId_Voltorb:
    case PokemonId_Electrode:
    case PokemonId_Exeggcute:
    case PokemonId_Exeggutor:
    case PokemonId_Cubone:
    case PokemonId_Marowak:
    case PokemonId_Hitmonlee:
    case PokemonId_Hitmonchan:
    case PokemonId_Lickitung:
    case PokemonId_Koffing:
    case PokemonId_Weezing:
    case PokemonId_Rhyhorn:
    case PokemonId_Rhydon:
    case PokemonId_Chansey:
    case PokemonId_Tangela:
    case PokemonId_Kangaskhan:
    case PokemonId_Horsea:
    case PokemonId_Seadra:
    case PokemonId_Goldeen:
    case PokemonId_Seaking:
    case PokemonId_Staryu:
    case PokemonId_Starmie:
    case PokemonId_MrMime:
    case PokemonId_Scyther:
    case PokemonId_Jynx:
    case PokemonId_Electabuzz:
    case PokemonId_Magmar:
    case PokemonId_Pinsir:
    case PokemonId_Tauros:
    case PokemonId_Magikarp:
    case PokemonId_Gyarados:
    case PokemonId_Lapras:
    case PokemonId_Ditto:
    case PokemonId_Eevee:
    case PokemonId_Vaporeon:
    case PokemonId_Jolteon:
    case PokemonId_Flareon:
    case PokemonId_Porygon:
    case PokemonId_Omanyte:
    case PokemonId_Omastar:
    case PokemonId_Kabuto:
    case PokemonId_Kabutops:
    case PokemonId_Aerodactyl:
    case PokemonId_Snorlax:
    case PokemonId_Articuno:
    case PokemonId_Zapdos:
    case PokemonId_Moltres:
    case PokemonId_Dratini:
    case PokemonId_Dragonair:
    case PokemonId_Dragonite:
    case PokemonId_Mewtwo:
    case PokemonId_Mew:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
