// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Item/FoodAttributes.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "FoodAttributes.pbobjc.h"
 #import "ItemEffect.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - FoodAttributesRoot

@implementation FoodAttributesRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ItemEffectRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - FoodAttributesRoot_FileDescriptor

static GPBFileDescriptor *FoodAttributesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings.Master.Item"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - FoodAttributes

@implementation FoodAttributes

@dynamic itemEffectArray, itemEffectArray_Count;
@dynamic itemEffectPercentArray, itemEffectPercentArray_Count;
@dynamic growthPercent;

typedef struct FoodAttributes__storage_ {
  uint32_t _has_storage_[1];
  float growthPercent;
  GPBEnumArray *itemEffectArray;
  GPBFloatArray *itemEffectPercentArray;
} FoodAttributes__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemEffectArray",
        .dataTypeSpecific.enumDescFunc = ItemEffect_EnumDescriptor,
        .number = FoodAttributes_FieldNumber_ItemEffectArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(FoodAttributes__storage_, itemEffectArray),
        .flags = GPBFieldRepeated | GPBFieldPacked | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "itemEffectPercentArray",
        .dataTypeSpecific.className = NULL,
        .number = FoodAttributes_FieldNumber_ItemEffectPercentArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(FoodAttributes__storage_, itemEffectPercentArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "growthPercent",
        .dataTypeSpecific.className = NULL,
        .number = FoodAttributes_FieldNumber_GrowthPercent,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FoodAttributes__storage_, growthPercent),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FoodAttributes class]
                                     rootClass:[FoodAttributesRoot class]
                                          file:FoodAttributesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FoodAttributes__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
