// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Item/FortModifierAttributes.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "FortModifierAttributes.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - FortModifierAttributesRoot

@implementation FortModifierAttributesRoot

@end

#pragma mark - FortModifierAttributesRoot_FileDescriptor

static GPBFileDescriptor *FortModifierAttributesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings.Master.Item"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - FortModifierAttributes

@implementation FortModifierAttributes

@dynamic modifierLifetimeSeconds;
@dynamic troyDiskNumPokemonSpawned;

typedef struct FortModifierAttributes__storage_ {
  uint32_t _has_storage_[1];
  int32_t modifierLifetimeSeconds;
  int32_t troyDiskNumPokemonSpawned;
} FortModifierAttributes__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "modifierLifetimeSeconds",
        .dataTypeSpecific.className = NULL,
        .number = FortModifierAttributes_FieldNumber_ModifierLifetimeSeconds,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FortModifierAttributes__storage_, modifierLifetimeSeconds),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "troyDiskNumPokemonSpawned",
        .dataTypeSpecific.className = NULL,
        .number = FortModifierAttributes_FieldNumber_TroyDiskNumPokemonSpawned,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FortModifierAttributes__storage_, troyDiskNumPokemonSpawned),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FortModifierAttributes class]
                                     rootClass:[FortModifierAttributesRoot class]
                                          file:FortModifierAttributesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FortModifierAttributes__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
