// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Platform/Responses/BuyItemPokeCoinsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Platform/Responses/BuyItemPokeCoinsResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - BuyItemPokeCoinsResponseRoot

@implementation BuyItemPokeCoinsResponseRoot

@end

#pragma mark - BuyItemPokeCoinsResponseRoot_FileDescriptor

static GPBFileDescriptor *BuyItemPokeCoinsResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Platform.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - BuyItemPokeCoinsResponse

@implementation BuyItemPokeCoinsResponse

@dynamic result;

typedef struct BuyItemPokeCoinsResponse__storage_ {
  uint32_t _has_storage_[1];
  BuyItemPokeCoinsResponse_Status result;
} BuyItemPokeCoinsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = BuyItemPokeCoinsResponse_Status_EnumDescriptor,
        .number = BuyItemPokeCoinsResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BuyItemPokeCoinsResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BuyItemPokeCoinsResponse class]
                                     rootClass:[BuyItemPokeCoinsResponseRoot class]
                                          file:BuyItemPokeCoinsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BuyItemPokeCoinsResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t BuyItemPokeCoinsResponse_Result_RawValue(BuyItemPokeCoinsResponse *message) {
  GPBDescriptor *descriptor = [BuyItemPokeCoinsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:BuyItemPokeCoinsResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetBuyItemPokeCoinsResponse_Result_RawValue(BuyItemPokeCoinsResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [BuyItemPokeCoinsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:BuyItemPokeCoinsResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum BuyItemPokeCoinsResponse_Status

GPBEnumDescriptor *BuyItemPokeCoinsResponse_Status_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Success\000NotEnoughPokecoins\000";
    static const int32_t values[] = {
        BuyItemPokeCoinsResponse_Status_Unknown,
        BuyItemPokeCoinsResponse_Status_Success,
        BuyItemPokeCoinsResponse_Status_NotEnoughPokecoins,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(BuyItemPokeCoinsResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:BuyItemPokeCoinsResponse_Status_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL BuyItemPokeCoinsResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case BuyItemPokeCoinsResponse_Status_Unknown:
    case BuyItemPokeCoinsResponse_Status_Success:
    case BuyItemPokeCoinsResponse_Status_NotEnoughPokecoins:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
