// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Platform/Responses/GetStoreItemsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Platform/Responses/GetStoreItemsResponse.pbobjc.h"
 #import "POGOProtos/Data/Player/Currency.pbobjc.h"
 #import "POGOProtos/Inventory/Item/ItemData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetStoreItemsResponseRoot

@implementation GetStoreItemsResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[CurrencyRoot extensionRegistry]];
    [registry addExtensions:[ItemDataRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetStoreItemsResponseRoot_FileDescriptor

static GPBFileDescriptor *GetStoreItemsResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Envelopes"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetStoreItemsResponse

@implementation GetStoreItemsResponse

@dynamic status;
@dynamic itemsArray, itemsArray_Count;
@dynamic playerCurrenciesArray, playerCurrenciesArray_Count;
@dynamic unknown4;

typedef struct GetStoreItemsResponse__storage_ {
  uint32_t _has_storage_[1];
  GetStoreItemsResponse_Status status;
  NSMutableArray *itemsArray;
  NSMutableArray *playerCurrenciesArray;
  NSString *unknown4;
} GetStoreItemsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = GetStoreItemsResponse_Status_EnumDescriptor,
        .number = GetStoreItemsResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse__storage_, status),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "itemsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GetStoreItemsResponse_StoreItem),
        .number = GetStoreItemsResponse_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse__storage_, itemsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "playerCurrenciesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Currency),
        .number = GetStoreItemsResponse_FieldNumber_PlayerCurrenciesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse__storage_, playerCurrenciesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown4",
        .dataTypeSpecific.className = NULL,
        .number = GetStoreItemsResponse_FieldNumber_Unknown4,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse__storage_, unknown4),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetStoreItemsResponse class]
                                     rootClass:[GetStoreItemsResponseRoot class]
                                          file:GetStoreItemsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetStoreItemsResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetStoreItemsResponse_Status_RawValue(GetStoreItemsResponse *message) {
  GPBDescriptor *descriptor = [GetStoreItemsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetStoreItemsResponse_FieldNumber_Status];
  return GPBGetMessageInt32Field(message, field);
}

void SetGetStoreItemsResponse_Status_RawValue(GetStoreItemsResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetStoreItemsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetStoreItemsResponse_FieldNumber_Status];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum GetStoreItemsResponse_Status

GPBEnumDescriptor *GetStoreItemsResponse_Status_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Undefined\000Okay\000";
    static const int32_t values[] = {
        GetStoreItemsResponse_Status_Undefined,
        GetStoreItemsResponse_Status_Okay,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetStoreItemsResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetStoreItemsResponse_Status_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetStoreItemsResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetStoreItemsResponse_Status_Undefined:
    case GetStoreItemsResponse_Status_Okay:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GetStoreItemsResponse_StoreItem

@implementation GetStoreItemsResponse_StoreItem

@dynamic itemId;
@dynamic isIap;
@dynamic hasCurrencyToBuy, currencyToBuy;
@dynamic hasYieldsCurrency, yieldsCurrency;
@dynamic hasYieldsItem, yieldsItem;
@dynamic tags, tags_Count;
@dynamic unknown7;

typedef struct GetStoreItemsResponse_StoreItem__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown7;
  NSString *itemId;
  Currency *currencyToBuy;
  Currency *yieldsCurrency;
  ItemData *yieldsItem;
  NSMutableDictionary *tags;
} GetStoreItemsResponse_StoreItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemId",
        .dataTypeSpecific.className = NULL,
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_ItemId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, itemId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isIap",
        .dataTypeSpecific.className = NULL,
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_IsIap,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "currencyToBuy",
        .dataTypeSpecific.className = GPBStringifySymbol(Currency),
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_CurrencyToBuy,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, currencyToBuy),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "yieldsCurrency",
        .dataTypeSpecific.className = GPBStringifySymbol(Currency),
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_YieldsCurrency,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, yieldsCurrency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "yieldsItem",
        .dataTypeSpecific.className = GPBStringifySymbol(ItemData),
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_YieldsItem,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, yieldsItem),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "tags",
        .dataTypeSpecific.className = NULL,
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_Tags,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, tags),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "unknown7",
        .dataTypeSpecific.className = NULL,
        .number = GetStoreItemsResponse_StoreItem_FieldNumber_Unknown7,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GetStoreItemsResponse_StoreItem__storage_, unknown7),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetStoreItemsResponse_StoreItem class]
                                     rootClass:[GetStoreItemsResponseRoot class]
                                          file:GetStoreItemsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetStoreItemsResponse_StoreItem__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
