// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Envelopes/ResponseEnvelope.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AuthTicket;
@class ResponseEnvelope_PlatformResponse;
GPB_ENUM_FWD_DECLARE(PlatformRequestType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ResponseEnvelope_StatusCode

typedef GPB_ENUM(ResponseEnvelope_StatusCode) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ResponseEnvelope_StatusCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ResponseEnvelope_StatusCode_Unknown = 0,

  /// valid response with no api url
  ResponseEnvelope_StatusCode_Ok = 1,

  /// the response envelope has api_url set and this response is valid
  ResponseEnvelope_StatusCode_OkRpcURLInResponse = 2,

  /// bad request
  ResponseEnvelope_StatusCode_BadRequest = 3,

  /// using unimplemented request or corrupt request
  ResponseEnvelope_StatusCode_InvalidRequest = 51,

  /// invalid platform request or corrupt platform request
  ResponseEnvelope_StatusCode_InvalidPlatformRequest = 52,

  /// a new rpc endpoint is available and you should redirect to there
  ResponseEnvelope_StatusCode_Redirect = 53,

  /// occurs when you send blank authinfo, or sending nonsense timings (ie LocationFix.timestampSnapshot == Signature.timestampSinceStart)
  ResponseEnvelope_StatusCode_SessionInvalidated = 100,

  /// occurs when the login token is invalid
  ResponseEnvelope_StatusCode_InvalidAuthToken = 102,
};

GPBEnumDescriptor *ResponseEnvelope_StatusCode_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ResponseEnvelope_StatusCode_IsValidValue(int32_t value);

#pragma mark - ResponseEnvelopeRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ResponseEnvelopeRoot : GPBRootObject
@end

#pragma mark - ResponseEnvelope

typedef GPB_ENUM(ResponseEnvelope_FieldNumber) {
  ResponseEnvelope_FieldNumber_StatusCode = 1,
  ResponseEnvelope_FieldNumber_RequestId = 2,
  ResponseEnvelope_FieldNumber_ApiURL = 3,
  ResponseEnvelope_FieldNumber_PlatformReturnsArray = 6,
  ResponseEnvelope_FieldNumber_AuthTicket = 7,
  ResponseEnvelope_FieldNumber_ReturnsArray = 100,
  ResponseEnvelope_FieldNumber_Error = 101,
};

@interface ResponseEnvelope : GPBMessage

@property(nonatomic, readwrite) ResponseEnvelope_StatusCode statusCode;

@property(nonatomic, readwrite) uint64_t requestId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *apiURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ResponseEnvelope_PlatformResponse*> *platformReturnsArray;
/// The number of items in @c platformReturnsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger platformReturnsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) AuthTicket *authTicket;
/// Test to see if @c authTicket has been set.
@property(nonatomic, readwrite) BOOL hasAuthTicket;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *returnsArray;
/// The number of items in @c returnsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger returnsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

@end

/// Fetches the raw value of a @c ResponseEnvelope's @c statusCode property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t ResponseEnvelope_StatusCode_RawValue(ResponseEnvelope *message);
/// Sets the raw value of an @c ResponseEnvelope's @c statusCode property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetResponseEnvelope_StatusCode_RawValue(ResponseEnvelope *message, int32_t value);

#pragma mark - ResponseEnvelope_PlatformResponse

typedef GPB_ENUM(ResponseEnvelope_PlatformResponse_FieldNumber) {
  ResponseEnvelope_PlatformResponse_FieldNumber_Type = 1,
  ResponseEnvelope_PlatformResponse_FieldNumber_Response = 2,
};

@interface ResponseEnvelope_PlatformResponse : GPBMessage

@property(nonatomic, readwrite) enum PlatformRequestType type;

@property(nonatomic, readwrite, copy, null_resettable) NSData *response;

@end

/// Fetches the raw value of a @c ResponseEnvelope_PlatformResponse's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t ResponseEnvelope_PlatformResponse_Type_RawValue(ResponseEnvelope_PlatformResponse *message);
/// Sets the raw value of an @c ResponseEnvelope_PlatformResponse's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetResponseEnvelope_PlatformResponse_Type_RawValue(ResponseEnvelope_PlatformResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
