// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Envelopes/Signature.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Signature_ActivityStatus;
@class Signature_AndroidGpsInfo;
@class Signature_DeviceInfo;
@class Signature_LocationFix;
@class Signature_SensorInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SignatureRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface SignatureRoot : GPBRootObject
@end

#pragma mark - Signature

typedef GPB_ENUM(Signature_FieldNumber) {
  Signature_FieldNumber_TimestampSinceStart = 2,
  Signature_FieldNumber_LocationFixArray = 4,
  Signature_FieldNumber_GpsInfo = 5,
  Signature_FieldNumber_SensorInfo = 7,
  Signature_FieldNumber_DeviceInfo = 8,
  Signature_FieldNumber_ActivityStatus = 9,
  Signature_FieldNumber_LocationHash1 = 10,
  Signature_FieldNumber_LocationHash2 = 20,
  Signature_FieldNumber_SessionHash = 22,
  Signature_FieldNumber_Timestamp = 23,
  Signature_FieldNumber_RequestHashArray = 24,
  Signature_FieldNumber_Unknown25 = 25,
};

@interface Signature : GPBMessage

/// in ms
@property(nonatomic, readwrite) uint64_t timestampSinceStart;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Signature_LocationFix*> *locationFixArray;
/// The number of items in @c locationFixArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger locationFixArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Signature_AndroidGpsInfo *gpsInfo;
/// Test to see if @c gpsInfo has been set.
@property(nonatomic, readwrite) BOOL hasGpsInfo;

@property(nonatomic, readwrite, strong, null_resettable) Signature_SensorInfo *sensorInfo;
/// Test to see if @c sensorInfo has been set.
@property(nonatomic, readwrite) BOOL hasSensorInfo;

@property(nonatomic, readwrite, strong, null_resettable) Signature_DeviceInfo *deviceInfo;
/// Test to see if @c deviceInfo has been set.
@property(nonatomic, readwrite) BOOL hasDeviceInfo;

@property(nonatomic, readwrite, strong, null_resettable) Signature_ActivityStatus *activityStatus;
/// Test to see if @c activityStatus has been set.
@property(nonatomic, readwrite) BOOL hasActivityStatus;

/// Location1 hashed signed based on the auth_token or auth_info - xxHash32
@property(nonatomic, readwrite) uint32_t locationHash1;

/// Location2 hashed (unsigned) - xxHash32
@property(nonatomic, readwrite) uint32_t locationHash2;

/// 16 bytes, unique per session
@property(nonatomic, readwrite, copy, null_resettable) NSData *sessionHash;

/// epoch timestamp in ms
@property(nonatomic, readwrite) uint64_t timestamp;

/// hashes of each request message in a hashArray signed based on the auth_token or auth_info - xxhash64
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *requestHashArray;
/// The number of items in @c requestHashArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger requestHashArray_Count;

/// for 0.33 its static -8537042734809897855 or 0x898654dd2753a481, generated via xxHash64("\\"b8fa9757195897aae92c53dbcf8a60fb3d86d745\\"".ToByteArray(), 0x88533787)
@property(nonatomic, readwrite) int64_t unknown25;

@end

#pragma mark - Signature_LocationFix

typedef GPB_ENUM(Signature_LocationFix_FieldNumber) {
  Signature_LocationFix_FieldNumber_Provider = 1,
  Signature_LocationFix_FieldNumber_TimestampSnapshot = 2,
  Signature_LocationFix_FieldNumber_Altitude = 4,
  Signature_LocationFix_FieldNumber_Latitude = 13,
  Signature_LocationFix_FieldNumber_Longitude = 14,
  Signature_LocationFix_FieldNumber_Speed = 18,
  Signature_LocationFix_FieldNumber_Course = 20,
  Signature_LocationFix_FieldNumber_HorizontalAccuracy = 21,
  Signature_LocationFix_FieldNumber_VerticalAccuracy = 22,
  Signature_LocationFix_FieldNumber_ProviderStatus = 26,
  Signature_LocationFix_FieldNumber_Floor = 27,
  Signature_LocationFix_FieldNumber_LocationType = 28,
};

@interface Signature_LocationFix : GPBMessage

/// "network", "gps", "fused", possibly others
@property(nonatomic, readwrite, copy, null_resettable) NSString *provider;

/// in ms since start
@property(nonatomic, readwrite) uint64_t timestampSnapshot;

/// Confirmed on android/ios
@property(nonatomic, readwrite) float altitude;

@property(nonatomic, readwrite) float latitude;

@property(nonatomic, readwrite) float longitude;

/// iOS only (-1 for no reading available, speed in m/s)
@property(nonatomic, readwrite) float speed;

/// iOS only (range seems to be -1 for not reading, and 0 to 360 for reading) confirmed by \@marcel
@property(nonatomic, readwrite) float course;

/// in meters, both on Android and iOS
@property(nonatomic, readwrite) float horizontalAccuracy;

/// iOS only 
@property(nonatomic, readwrite) float verticalAccuracy;

/// Usually 3 (possibly GPS status: 1 = no fix, 2 = acquiring/inaccurate, 3 = fix acquired)
@property(nonatomic, readwrite) uint64_t providerStatus;

/// On iOS there are some LocationFixes with unk26=1 and everything else empty
@property(nonatomic, readwrite) uint32_t floor;

/// Always 1 (if there is data at all)
@property(nonatomic, readwrite) uint64_t locationType;

@end

#pragma mark - Signature_AndroidGpsInfo

typedef GPB_ENUM(Signature_AndroidGpsInfo_FieldNumber) {
  Signature_AndroidGpsInfo_FieldNumber_TimeToFix = 1,
  Signature_AndroidGpsInfo_FieldNumber_SatellitesPrnArray = 2,
  Signature_AndroidGpsInfo_FieldNumber_AzimuthArray = 3,
  Signature_AndroidGpsInfo_FieldNumber_ElevationArray = 4,
  Signature_AndroidGpsInfo_FieldNumber_SnrArray = 5,
  Signature_AndroidGpsInfo_FieldNumber_HasAlmanacArray = 6,
  Signature_AndroidGpsInfo_FieldNumber_HasEphemerisArray = 7,
  Signature_AndroidGpsInfo_FieldNumber_UsedInFixArray = 8,
};

/// don't really care about this since we're not using it
@interface Signature_AndroidGpsInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t timeToFix;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *satellitesPrnArray;
/// The number of items in @c satellitesPrnArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger satellitesPrnArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *azimuthArray;
/// The number of items in @c azimuthArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger azimuthArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *elevationArray;
/// The number of items in @c elevationArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger elevationArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *snrArray;
/// The number of items in @c snrArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger snrArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *hasAlmanacArray;
/// The number of items in @c hasAlmanacArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger hasAlmanacArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *hasEphemerisArray;
/// The number of items in @c hasEphemerisArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger hasEphemerisArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *usedInFixArray;
/// The number of items in @c usedInFixArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger usedInFixArray_Count;

@end

#pragma mark - Signature_SensorInfo

typedef GPB_ENUM(Signature_SensorInfo_FieldNumber) {
  Signature_SensorInfo_FieldNumber_TimestampSnapshot = 1,
  Signature_SensorInfo_FieldNumber_LinearAccelerationX = 3,
  Signature_SensorInfo_FieldNumber_LinearAccelerationY = 4,
  Signature_SensorInfo_FieldNumber_LinearAccelerationZ = 5,
  Signature_SensorInfo_FieldNumber_MagneticFieldX = 6,
  Signature_SensorInfo_FieldNumber_MagneticFieldY = 7,
  Signature_SensorInfo_FieldNumber_MagneticFieldZ = 8,
  Signature_SensorInfo_FieldNumber_RotationVectorX = 10,
  Signature_SensorInfo_FieldNumber_RotationVectorY = 11,
  Signature_SensorInfo_FieldNumber_RotationVectorZ = 12,
  Signature_SensorInfo_FieldNumber_GyroscopeRawX = 13,
  Signature_SensorInfo_FieldNumber_GyroscopeRawY = 14,
  Signature_SensorInfo_FieldNumber_GyroscopeRawZ = 15,
  Signature_SensorInfo_FieldNumber_GravityX = 16,
  Signature_SensorInfo_FieldNumber_GravityY = 17,
  Signature_SensorInfo_FieldNumber_GravityZ = 18,
  Signature_SensorInfo_FieldNumber_AccelerometerAxes = 19,
};

@interface Signature_SensorInfo : GPBMessage

/// in ms since start
@property(nonatomic, readwrite) uint64_t timestampSnapshot;

@property(nonatomic, readwrite) double linearAccelerationX;

@property(nonatomic, readwrite) double linearAccelerationY;

@property(nonatomic, readwrite) double linearAccelerationZ;

@property(nonatomic, readwrite) double magneticFieldX;

@property(nonatomic, readwrite) double magneticFieldY;

@property(nonatomic, readwrite) double magneticFieldZ;

@property(nonatomic, readwrite) double rotationVectorX;

@property(nonatomic, readwrite) double rotationVectorY;

@property(nonatomic, readwrite) double rotationVectorZ;

@property(nonatomic, readwrite) double gyroscopeRawX;

@property(nonatomic, readwrite) double gyroscopeRawY;

@property(nonatomic, readwrite) double gyroscopeRawZ;

@property(nonatomic, readwrite) double gravityX;

@property(nonatomic, readwrite) double gravityY;

@property(nonatomic, readwrite) double gravityZ;

/// Always 3
@property(nonatomic, readwrite) uint64_t accelerometerAxes;

@end

#pragma mark - Signature_DeviceInfo

typedef GPB_ENUM(Signature_DeviceInfo_FieldNumber) {
  Signature_DeviceInfo_FieldNumber_DeviceId = 1,
  Signature_DeviceInfo_FieldNumber_AndroidBoardName = 2,
  Signature_DeviceInfo_FieldNumber_AndroidBootloader = 3,
  Signature_DeviceInfo_FieldNumber_DeviceBrand = 4,
  Signature_DeviceInfo_FieldNumber_DeviceModel = 5,
  Signature_DeviceInfo_FieldNumber_DeviceModelIdentifier = 6,
  Signature_DeviceInfo_FieldNumber_DeviceModelBoot = 7,
  Signature_DeviceInfo_FieldNumber_HardwareManufacturer = 8,
  Signature_DeviceInfo_FieldNumber_HardwareModel = 9,
  Signature_DeviceInfo_FieldNumber_FirmwareBrand = 10,
  Signature_DeviceInfo_FieldNumber_FirmwareTags = 12,
  Signature_DeviceInfo_FieldNumber_FirmwareType = 13,
  Signature_DeviceInfo_FieldNumber_FirmwareFingerprint = 14,
};

@interface Signature_DeviceInfo : GPBMessage

/// Hex string
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *androidBoardName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *androidBootloader;

/// On Android: product.brand
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

/// On Android: product.device
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

/// Android only, build.display.id
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModelIdentifier;

/// On Android: boot.hardware
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModelBoot;

/// On Android: product.manufacturer
@property(nonatomic, readwrite, copy, null_resettable) NSString *hardwareManufacturer;

/// On Android: product.model
@property(nonatomic, readwrite, copy, null_resettable) NSString *hardwareModel;

/// On Android: product.name, on iOS: "iPhone OS"
@property(nonatomic, readwrite, copy, null_resettable) NSString *firmwareBrand;

/// Android only, build.tags
@property(nonatomic, readwrite, copy, null_resettable) NSString *firmwareTags;

/// On Android: build.type, on iOS instead: iOS version
@property(nonatomic, readwrite, copy, null_resettable) NSString *firmwareType;

/// Android only, build.fingerprint
@property(nonatomic, readwrite, copy, null_resettable) NSString *firmwareFingerprint;

@end

#pragma mark - Signature_ActivityStatus

typedef GPB_ENUM(Signature_ActivityStatus_FieldNumber) {
  Signature_ActivityStatus_FieldNumber_StartTimeMs = 1,
  Signature_ActivityStatus_FieldNumber_UnknownStatus = 2,
  Signature_ActivityStatus_FieldNumber_Walking = 3,
  Signature_ActivityStatus_FieldNumber_Running = 4,
  Signature_ActivityStatus_FieldNumber_Stationary = 5,
  Signature_ActivityStatus_FieldNumber_Automotive = 6,
  Signature_ActivityStatus_FieldNumber_Tilting = 7,
  Signature_ActivityStatus_FieldNumber_Cycling = 8,
  Signature_ActivityStatus_FieldNumber_Status = 9,
};

/// Only used in iOS - Android just sends an empty version
@interface Signature_ActivityStatus : GPBMessage

/// all of these had 1 as their value
@property(nonatomic, readwrite) uint64_t startTimeMs;

@property(nonatomic, readwrite) BOOL unknownStatus;

@property(nonatomic, readwrite) BOOL walking;

@property(nonatomic, readwrite) BOOL running;

@property(nonatomic, readwrite) BOOL stationary;

@property(nonatomic, readwrite) BOOL automotive;

@property(nonatomic, readwrite) BOOL tilting;

@property(nonatomic, readwrite) BOOL cycling;

@property(nonatomic, readwrite, copy, null_resettable) NSData *status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
