// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/AddFortModifierResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/AddFortModifierResponse.pbobjc.h"
 #import "POGOProtos/Networking/Responses/FortDetailsResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - AddFortModifierResponseRoot

@implementation AddFortModifierResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[FortDetailsResponseRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - AddFortModifierResponseRoot_FileDescriptor

static GPBFileDescriptor *AddFortModifierResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - AddFortModifierResponse

@implementation AddFortModifierResponse

@dynamic result;
@dynamic hasFortDetails, fortDetails;

typedef struct AddFortModifierResponse__storage_ {
  uint32_t _has_storage_[1];
  AddFortModifierResponse_Result result;
  FortDetailsResponse *fortDetails;
} AddFortModifierResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = AddFortModifierResponse_Result_EnumDescriptor,
        .number = AddFortModifierResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AddFortModifierResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "fortDetails",
        .dataTypeSpecific.className = GPBStringifySymbol(FortDetailsResponse),
        .number = AddFortModifierResponse_FieldNumber_FortDetails,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AddFortModifierResponse__storage_, fortDetails),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AddFortModifierResponse class]
                                     rootClass:[AddFortModifierResponseRoot class]
                                          file:AddFortModifierResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AddFortModifierResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t AddFortModifierResponse_Result_RawValue(AddFortModifierResponse *message) {
  GPBDescriptor *descriptor = [AddFortModifierResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AddFortModifierResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetAddFortModifierResponse_Result_RawValue(AddFortModifierResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [AddFortModifierResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AddFortModifierResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum AddFortModifierResponse_Result

GPBEnumDescriptor *AddFortModifierResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "NoResultSet\000Success\000FortAlreadyHasModifi"
        "er\000TooFarAway\000NoItemInInventory\000";
    static const int32_t values[] = {
        AddFortModifierResponse_Result_NoResultSet,
        AddFortModifierResponse_Result_Success,
        AddFortModifierResponse_Result_FortAlreadyHasModifier,
        AddFortModifierResponse_Result_TooFarAway,
        AddFortModifierResponse_Result_NoItemInInventory,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(AddFortModifierResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:AddFortModifierResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL AddFortModifierResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case AddFortModifierResponse_Result_NoResultSet:
    case AddFortModifierResponse_Result_Success:
    case AddFortModifierResponse_Result_FortAlreadyHasModifier:
    case AddFortModifierResponse_Result_TooFarAway:
    case AddFortModifierResponse_Result_NoItemInInventory:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
