// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/FortDetailsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FortModifier;
@class PokemonData;
GPB_ENUM_FWD_DECLARE(FortType);
GPB_ENUM_FWD_DECLARE(TeamColor);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FortDetailsResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface FortDetailsResponseRoot : GPBRootObject
@end

#pragma mark - FortDetailsResponse

typedef GPB_ENUM(FortDetailsResponse_FieldNumber) {
  FortDetailsResponse_FieldNumber_FortId = 1,
  FortDetailsResponse_FieldNumber_TeamColor = 2,
  FortDetailsResponse_FieldNumber_PokemonData = 3,
  FortDetailsResponse_FieldNumber_Name = 4,
  FortDetailsResponse_FieldNumber_ImageUrlsArray = 5,
  FortDetailsResponse_FieldNumber_Fp = 6,
  FortDetailsResponse_FieldNumber_Stamina = 7,
  FortDetailsResponse_FieldNumber_MaxStamina = 8,
  FortDetailsResponse_FieldNumber_Type = 9,
  FortDetailsResponse_FieldNumber_Latitude = 10,
  FortDetailsResponse_FieldNumber_Longitude = 11,
  FortDetailsResponse_FieldNumber_Description_p = 12,
  FortDetailsResponse_FieldNumber_ModifiersArray = 13,
};

@interface FortDetailsResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) enum TeamColor teamColor;

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *pokemonData;
/// Test to see if @c pokemonData has been set.
@property(nonatomic, readwrite) BOOL hasPokemonData;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imageUrlsArray;
/// The number of items in @c imageUrlsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger imageUrlsArray_Count;

@property(nonatomic, readwrite) int32_t fp;

@property(nonatomic, readwrite) int32_t stamina;

@property(nonatomic, readwrite) int32_t maxStamina;

@property(nonatomic, readwrite) enum FortType type;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FortModifier*> *modifiersArray;
/// The number of items in @c modifiersArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger modifiersArray_Count;

@end

/// Fetches the raw value of a @c FortDetailsResponse's @c teamColor property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t FortDetailsResponse_TeamColor_RawValue(FortDetailsResponse *message);
/// Sets the raw value of an @c FortDetailsResponse's @c teamColor property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetFortDetailsResponse_TeamColor_RawValue(FortDetailsResponse *message, int32_t value);

/// Fetches the raw value of a @c FortDetailsResponse's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t FortDetailsResponse_Type_RawValue(FortDetailsResponse *message);
/// Sets the raw value of an @c FortDetailsResponse's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetFortDetailsResponse_Type_RawValue(FortDetailsResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
