// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetIncensePokemonResponse.pbobjc.h"
 #import "PokemonId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetIncensePokemonResponseRoot

@implementation GetIncensePokemonResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PokemonIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetIncensePokemonResponseRoot_FileDescriptor

static GPBFileDescriptor *GetIncensePokemonResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetIncensePokemonResponse

@implementation GetIncensePokemonResponse

@dynamic result;
@dynamic pokemonId;
@dynamic latitude;
@dynamic longitude;
@dynamic encounterLocation;
@dynamic encounterId;
@dynamic disappearTimestampMs;

typedef struct GetIncensePokemonResponse__storage_ {
  uint32_t _has_storage_[1];
  GetIncensePokemonResponse_Result result;
  PokemonId pokemonId;
  NSString *encounterLocation;
  double latitude;
  double longitude;
  uint64_t encounterId;
  int64_t disappearTimestampMs;
} GetIncensePokemonResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = GetIncensePokemonResponse_Result_EnumDescriptor,
        .number = GetIncensePokemonResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "pokemonId",
        .dataTypeSpecific.enumDescFunc = PokemonId_EnumDescriptor,
        .number = GetIncensePokemonResponse_FieldNumber_PokemonId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, pokemonId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = GetIncensePokemonResponse_FieldNumber_Latitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = GetIncensePokemonResponse_FieldNumber_Longitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "encounterLocation",
        .dataTypeSpecific.className = NULL,
        .number = GetIncensePokemonResponse_FieldNumber_EncounterLocation,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, encounterLocation),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = GetIncensePokemonResponse_FieldNumber_EncounterId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, encounterId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "disappearTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = GetIncensePokemonResponse_FieldNumber_DisappearTimestampMs,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GetIncensePokemonResponse__storage_, disappearTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetIncensePokemonResponse class]
                                     rootClass:[GetIncensePokemonResponseRoot class]
                                          file:GetIncensePokemonResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetIncensePokemonResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetIncensePokemonResponse_Result_RawValue(GetIncensePokemonResponse *message) {
  GPBDescriptor *descriptor = [GetIncensePokemonResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetIncensePokemonResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetGetIncensePokemonResponse_Result_RawValue(GetIncensePokemonResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetIncensePokemonResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetIncensePokemonResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t GetIncensePokemonResponse_PokemonId_RawValue(GetIncensePokemonResponse *message) {
  GPBDescriptor *descriptor = [GetIncensePokemonResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetIncensePokemonResponse_FieldNumber_PokemonId];
  return GPBGetMessageInt32Field(message, field);
}

void SetGetIncensePokemonResponse_PokemonId_RawValue(GetIncensePokemonResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetIncensePokemonResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetIncensePokemonResponse_FieldNumber_PokemonId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum GetIncensePokemonResponse_Result

GPBEnumDescriptor *GetIncensePokemonResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "IncenseEncounterUnknown\000IncenseEncounter"
        "Available\000IncenseEncounterNotAvailable\000";
    static const int32_t values[] = {
        GetIncensePokemonResponse_Result_IncenseEncounterUnknown,
        GetIncensePokemonResponse_Result_IncenseEncounterAvailable,
        GetIncensePokemonResponse_Result_IncenseEncounterNotAvailable,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetIncensePokemonResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetIncensePokemonResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetIncensePokemonResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetIncensePokemonResponse_Result_IncenseEncounterUnknown:
    case GetIncensePokemonResponse_Result_IncenseEncounterAvailable:
    case GetIncensePokemonResponse_Result_IncenseEncounterNotAvailable:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
