// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetMapObjectsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetMapObjectsResponse.pbobjc.h"
 #import "MapCell.pbobjc.h"
 #import "MapObjectsStatus.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetMapObjectsResponseRoot

@implementation GetMapObjectsResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[MapCellRoot extensionRegistry]];
    [registry addExtensions:[MapObjectsStatusRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetMapObjectsResponseRoot_FileDescriptor

static GPBFileDescriptor *GetMapObjectsResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetMapObjectsResponse

@implementation GetMapObjectsResponse

@dynamic mapCellsArray, mapCellsArray_Count;
@dynamic status;

typedef struct GetMapObjectsResponse__storage_ {
  uint32_t _has_storage_[1];
  MapObjectsStatus status;
  NSMutableArray *mapCellsArray;
} GetMapObjectsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "mapCellsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MapCell),
        .number = GetMapObjectsResponse_FieldNumber_MapCellsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetMapObjectsResponse__storage_, mapCellsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = MapObjectsStatus_EnumDescriptor,
        .number = GetMapObjectsResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetMapObjectsResponse__storage_, status),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetMapObjectsResponse class]
                                     rootClass:[GetMapObjectsResponseRoot class]
                                          file:GetMapObjectsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetMapObjectsResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetMapObjectsResponse_Status_RawValue(GetMapObjectsResponse *message) {
  GPBDescriptor *descriptor = [GetMapObjectsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetMapObjectsResponse_FieldNumber_Status];
  return GPBGetMessageInt32Field(message, field);
}

void SetGetMapObjectsResponse_Status_RawValue(GetMapObjectsResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetMapObjectsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetMapObjectsResponse_FieldNumber_Status];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
