// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/StartGymBattleResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "StartGymBattleResponse.pbobjc.h"
 #import "BattleLog.pbobjc.h"
 #import "BattleParticipant.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - StartGymBattleResponseRoot

@implementation StartGymBattleResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[BattleLogRoot extensionRegistry]];
    [registry addExtensions:[BattleParticipantRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - StartGymBattleResponseRoot_FileDescriptor

static GPBFileDescriptor *StartGymBattleResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - StartGymBattleResponse

@implementation StartGymBattleResponse

@dynamic result;
@dynamic battleStartTimestampMs;
@dynamic battleEndTimestampMs;
@dynamic battleId;
@dynamic hasDefender, defender;
@dynamic hasBattleLog, battleLog;

typedef struct StartGymBattleResponse__storage_ {
  uint32_t _has_storage_[1];
  StartGymBattleResponse_Result result;
  NSString *battleId;
  BattleParticipant *defender;
  BattleLog *battleLog;
  int64_t battleStartTimestampMs;
  int64_t battleEndTimestampMs;
} StartGymBattleResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = StartGymBattleResponse_Result_EnumDescriptor,
        .number = StartGymBattleResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "battleStartTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = StartGymBattleResponse_FieldNumber_BattleStartTimestampMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, battleStartTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "battleEndTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = StartGymBattleResponse_FieldNumber_BattleEndTimestampMs,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, battleEndTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "battleId",
        .dataTypeSpecific.className = NULL,
        .number = StartGymBattleResponse_FieldNumber_BattleId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, battleId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "defender",
        .dataTypeSpecific.className = GPBStringifySymbol(BattleParticipant),
        .number = StartGymBattleResponse_FieldNumber_Defender,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, defender),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "battleLog",
        .dataTypeSpecific.className = GPBStringifySymbol(BattleLog),
        .number = StartGymBattleResponse_FieldNumber_BattleLog,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(StartGymBattleResponse__storage_, battleLog),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[StartGymBattleResponse class]
                                     rootClass:[StartGymBattleResponseRoot class]
                                          file:StartGymBattleResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(StartGymBattleResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t StartGymBattleResponse_Result_RawValue(StartGymBattleResponse *message) {
  GPBDescriptor *descriptor = [StartGymBattleResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:StartGymBattleResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetStartGymBattleResponse_Result_RawValue(StartGymBattleResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [StartGymBattleResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:StartGymBattleResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum StartGymBattleResponse_Result

GPBEnumDescriptor *StartGymBattleResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unset\000Success\000ErrorGymNotFound\000ErrorGymN"
        "eutral\000ErrorGymWrongTeam\000ErrorGymEmpty\000E"
        "rrorInvalidDefender\000ErrorTrainingInvalid"
        "AttackerCount\000ErrorAllPokemonFainted\000Err"
        "orTooManyBattles\000ErrorTooManyPlayers\000Err"
        "orGymBattleLockout\000ErrorPlayerBelowMinim"
        "umLevel\000ErrorNotInRange\000";
    static const int32_t values[] = {
        StartGymBattleResponse_Result_Unset,
        StartGymBattleResponse_Result_Success,
        StartGymBattleResponse_Result_ErrorGymNotFound,
        StartGymBattleResponse_Result_ErrorGymNeutral,
        StartGymBattleResponse_Result_ErrorGymWrongTeam,
        StartGymBattleResponse_Result_ErrorGymEmpty,
        StartGymBattleResponse_Result_ErrorInvalidDefender,
        StartGymBattleResponse_Result_ErrorTrainingInvalidAttackerCount,
        StartGymBattleResponse_Result_ErrorAllPokemonFainted,
        StartGymBattleResponse_Result_ErrorTooManyBattles,
        StartGymBattleResponse_Result_ErrorTooManyPlayers,
        StartGymBattleResponse_Result_ErrorGymBattleLockout,
        StartGymBattleResponse_Result_ErrorPlayerBelowMinimumLevel,
        StartGymBattleResponse_Result_ErrorNotInRange,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(StartGymBattleResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:StartGymBattleResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL StartGymBattleResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case StartGymBattleResponse_Result_Unset:
    case StartGymBattleResponse_Result_Success:
    case StartGymBattleResponse_Result_ErrorGymNotFound:
    case StartGymBattleResponse_Result_ErrorGymNeutral:
    case StartGymBattleResponse_Result_ErrorGymWrongTeam:
    case StartGymBattleResponse_Result_ErrorGymEmpty:
    case StartGymBattleResponse_Result_ErrorInvalidDefender:
    case StartGymBattleResponse_Result_ErrorTrainingInvalidAttackerCount:
    case StartGymBattleResponse_Result_ErrorAllPokemonFainted:
    case StartGymBattleResponse_Result_ErrorTooManyBattles:
    case StartGymBattleResponse_Result_ErrorTooManyPlayers:
    case StartGymBattleResponse_Result_ErrorGymBattleLockout:
    case StartGymBattleResponse_Result_ErrorPlayerBelowMinimumLevel:
    case StartGymBattleResponse_Result_ErrorNotInRange:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
