// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/UseItemEggIncubatorResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EggIncubator;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UseItemEggIncubatorResponse_Result

typedef GPB_ENUM(UseItemEggIncubatorResponse_Result) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  UseItemEggIncubatorResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  UseItemEggIncubatorResponse_Result_Unset = 0,
  UseItemEggIncubatorResponse_Result_Success = 1,
  UseItemEggIncubatorResponse_Result_ErrorIncubatorNotFound = 2,
  UseItemEggIncubatorResponse_Result_ErrorPokemonEggNotFound = 3,
  UseItemEggIncubatorResponse_Result_ErrorPokemonIdNotEgg = 4,
  UseItemEggIncubatorResponse_Result_ErrorIncubatorAlreadyInUse = 5,
  UseItemEggIncubatorResponse_Result_ErrorPokemonAlreadyIncubating = 6,
  UseItemEggIncubatorResponse_Result_ErrorIncubatorNoUsesRemaining = 7,
};

GPBEnumDescriptor *UseItemEggIncubatorResponse_Result_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL UseItemEggIncubatorResponse_Result_IsValidValue(int32_t value);

#pragma mark - UseItemEggIncubatorResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface UseItemEggIncubatorResponseRoot : GPBRootObject
@end

#pragma mark - UseItemEggIncubatorResponse

typedef GPB_ENUM(UseItemEggIncubatorResponse_FieldNumber) {
  UseItemEggIncubatorResponse_FieldNumber_Result = 1,
  UseItemEggIncubatorResponse_FieldNumber_EggIncubator = 2,
};

@interface UseItemEggIncubatorResponse : GPBMessage

@property(nonatomic, readwrite) UseItemEggIncubatorResponse_Result result;

@property(nonatomic, readwrite, strong, null_resettable) EggIncubator *eggIncubator;
/// Test to see if @c eggIncubator has been set.
@property(nonatomic, readwrite) BOOL hasEggIncubator;

@end

/// Fetches the raw value of a @c UseItemEggIncubatorResponse's @c result property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t UseItemEggIncubatorResponse_Result_RawValue(UseItemEggIncubatorResponse *message);
/// Sets the raw value of an @c UseItemEggIncubatorResponse's @c result property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetUseItemEggIncubatorResponse_Result_RawValue(UseItemEggIncubatorResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
