// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/UseItemPotionResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UseItemPotionResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UseItemPotionResponseRoot

@implementation UseItemPotionResponseRoot

@end

#pragma mark - UseItemPotionResponseRoot_FileDescriptor

static GPBFileDescriptor *UseItemPotionResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UseItemPotionResponse

@implementation UseItemPotionResponse

@dynamic result;
@dynamic stamina;

typedef struct UseItemPotionResponse__storage_ {
  uint32_t _has_storage_[1];
  UseItemPotionResponse_Result result;
  int32_t stamina;
} UseItemPotionResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = UseItemPotionResponse_Result_EnumDescriptor,
        .number = UseItemPotionResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UseItemPotionResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "stamina",
        .dataTypeSpecific.className = NULL,
        .number = UseItemPotionResponse_FieldNumber_Stamina,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UseItemPotionResponse__storage_, stamina),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UseItemPotionResponse class]
                                     rootClass:[UseItemPotionResponseRoot class]
                                          file:UseItemPotionResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UseItemPotionResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UseItemPotionResponse_Result_RawValue(UseItemPotionResponse *message) {
  GPBDescriptor *descriptor = [UseItemPotionResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UseItemPotionResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetUseItemPotionResponse_Result_RawValue(UseItemPotionResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [UseItemPotionResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UseItemPotionResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum UseItemPotionResponse_Result

GPBEnumDescriptor *UseItemPotionResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unset\000Success\000ErrorNoPokemon\000ErrorCannot"
        "Use\000ErrorDeployedToFort\000";
    static const int32_t values[] = {
        UseItemPotionResponse_Result_Unset,
        UseItemPotionResponse_Result_Success,
        UseItemPotionResponse_Result_ErrorNoPokemon,
        UseItemPotionResponse_Result_ErrorCannotUse,
        UseItemPotionResponse_Result_ErrorDeployedToFort,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(UseItemPotionResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:UseItemPotionResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL UseItemPotionResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case UseItemPotionResponse_Result_Unset:
    case UseItemPotionResponse_Result_Success:
    case UseItemPotionResponse_Result_ErrorNoPokemon:
    case UseItemPotionResponse_Result_ErrorCannotUse:
    case UseItemPotionResponse_Result_ErrorDeployedToFort:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
