// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppliedItem.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "AppliedItem.pbobjc.h"
 #import "ItemId.pbobjc.h"
 #import "ItemType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - AppliedItemRoot

@implementation AppliedItemRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ItemIdRoot extensionRegistry]];
    [registry addExtensions:[ItemTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - AppliedItemRoot_FileDescriptor

static GPBFileDescriptor *AppliedItemRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Inventory"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - AppliedItem

@implementation AppliedItem

@dynamic itemId;
@dynamic itemType;
@dynamic expireMs;
@dynamic appliedMs;

typedef struct AppliedItem__storage_ {
  uint32_t _has_storage_[1];
  ItemId itemId;
  ItemType itemType;
  int64_t expireMs;
  int64_t appliedMs;
} AppliedItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemId",
        .dataTypeSpecific.enumDescFunc = ItemId_EnumDescriptor,
        .number = AppliedItem_FieldNumber_ItemId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AppliedItem__storage_, itemId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "itemType",
        .dataTypeSpecific.enumDescFunc = ItemType_EnumDescriptor,
        .number = AppliedItem_FieldNumber_ItemType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AppliedItem__storage_, itemType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "expireMs",
        .dataTypeSpecific.className = NULL,
        .number = AppliedItem_FieldNumber_ExpireMs,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AppliedItem__storage_, expireMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "appliedMs",
        .dataTypeSpecific.className = NULL,
        .number = AppliedItem_FieldNumber_AppliedMs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(AppliedItem__storage_, appliedMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AppliedItem class]
                                     rootClass:[AppliedItemRoot class]
                                          file:AppliedItemRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AppliedItem__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t AppliedItem_ItemId_RawValue(AppliedItem *message) {
  GPBDescriptor *descriptor = [AppliedItem descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AppliedItem_FieldNumber_ItemId];
  return GPBGetMessageInt32Field(message, field);
}

void SetAppliedItem_ItemId_RawValue(AppliedItem *message, int32_t value) {
  GPBDescriptor *descriptor = [AppliedItem descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AppliedItem_FieldNumber_ItemId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t AppliedItem_ItemType_RawValue(AppliedItem *message) {
  GPBDescriptor *descriptor = [AppliedItem descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AppliedItem_FieldNumber_ItemType];
  return GPBGetMessageInt32Field(message, field);
}

void SetAppliedItem_ItemType_RawValue(AppliedItem *message, int32_t value) {
  GPBDescriptor *descriptor = [AppliedItem descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:AppliedItem_FieldNumber_ItemType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
