// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Inventory/EggIncubator.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(EggIncubatorType);
GPB_ENUM_FWD_DECLARE(ItemId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EggIncubatorRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface EggIncubatorRoot : GPBRootObject
@end

#pragma mark - EggIncubator

typedef GPB_ENUM(EggIncubator_FieldNumber) {
  EggIncubator_FieldNumber_Id_p = 1,
  EggIncubator_FieldNumber_ItemId = 2,
  EggIncubator_FieldNumber_IncubatorType = 3,
  EggIncubator_FieldNumber_UsesRemaining = 4,
  EggIncubator_FieldNumber_PokemonId = 5,
  EggIncubator_FieldNumber_StartKmWalked = 6,
  EggIncubator_FieldNumber_TargetKmWalked = 7,
};

@interface EggIncubator : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite) enum EggIncubatorType incubatorType;

@property(nonatomic, readwrite) int32_t usesRemaining;

/// TODO: Check if is PokemonType
@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite) double startKmWalked;

@property(nonatomic, readwrite) double targetKmWalked;

@end

/// Fetches the raw value of a @c EggIncubator's @c itemId property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t EggIncubator_ItemId_RawValue(EggIncubator *message);
/// Sets the raw value of an @c EggIncubator's @c itemId property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetEggIncubator_ItemId_RawValue(EggIncubator *message, int32_t value);

/// Fetches the raw value of a @c EggIncubator's @c incubatorType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t EggIncubator_IncubatorType_RawValue(EggIncubator *message);
/// Sets the raw value of an @c EggIncubator's @c incubatorType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetEggIncubator_IncubatorType_RawValue(EggIncubator *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
