// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/Pokemon/WildPokemon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PokemonData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WildPokemonRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface WildPokemonRoot : GPBRootObject
@end

#pragma mark - WildPokemon

typedef GPB_ENUM(WildPokemon_FieldNumber) {
  WildPokemon_FieldNumber_EncounterId = 1,
  WildPokemon_FieldNumber_LastModifiedTimestampMs = 2,
  WildPokemon_FieldNumber_Latitude = 3,
  WildPokemon_FieldNumber_Longitude = 4,
  WildPokemon_FieldNumber_SpawnPointId = 5,
  WildPokemon_FieldNumber_PokemonData = 7,
  WildPokemon_FieldNumber_TimeTillHiddenMs = 11,
};

@interface WildPokemon : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite) int64_t lastModifiedTimestampMs;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *pokemonData;
/// Test to see if @c pokemonData has been set.
@property(nonatomic, readwrite) BOOL hasPokemonData;

@property(nonatomic, readwrite) int32_t timeTillHiddenMs;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
