// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/CatchPokemonMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ItemId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CatchPokemonMessageRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface CatchPokemonMessageRoot : GPBRootObject
@end

#pragma mark - CatchPokemonMessage

typedef GPB_ENUM(CatchPokemonMessage_FieldNumber) {
  CatchPokemonMessage_FieldNumber_EncounterId = 1,
  CatchPokemonMessage_FieldNumber_Pokeball = 2,
  CatchPokemonMessage_FieldNumber_NormalizedReticleSize = 3,
  CatchPokemonMessage_FieldNumber_SpawnPointId = 4,
  CatchPokemonMessage_FieldNumber_HitPokemon = 5,
  CatchPokemonMessage_FieldNumber_SpinModifier = 6,
  CatchPokemonMessage_FieldNumber_NormalizedHitPosition = 7,
};

@interface CatchPokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite) enum ItemId pokeball;

@property(nonatomic, readwrite) double normalizedReticleSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite) BOOL hitPokemon;

@property(nonatomic, readwrite) double spinModifier;

@property(nonatomic, readwrite) double normalizedHitPosition;

@end

/// Fetches the raw value of a @c CatchPokemonMessage's @c pokeball property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t CatchPokemonMessage_Pokeball_RawValue(CatchPokemonMessage *message);
/// Sets the raw value of an @c CatchPokemonMessage's @c pokeball property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetCatchPokemonMessage_Pokeball_RawValue(CatchPokemonMessage *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
