// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/FortRecallPokemonMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "FortRecallPokemonMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - FortRecallPokemonMessageRoot

@implementation FortRecallPokemonMessageRoot

@end

#pragma mark - FortRecallPokemonMessageRoot_FileDescriptor

static GPBFileDescriptor *FortRecallPokemonMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - FortRecallPokemonMessage

@implementation FortRecallPokemonMessage

@dynamic fortId;
@dynamic pokemonId;
@dynamic playerLatitude;
@dynamic playerLongitude;

typedef struct FortRecallPokemonMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *fortId;
  uint64_t pokemonId;
  double playerLatitude;
  double playerLongitude;
} FortRecallPokemonMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortId",
        .dataTypeSpecific.className = NULL,
        .number = FortRecallPokemonMessage_FieldNumber_FortId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FortRecallPokemonMessage__storage_, fortId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pokemonId",
        .dataTypeSpecific.className = NULL,
        .number = FortRecallPokemonMessage_FieldNumber_PokemonId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FortRecallPokemonMessage__storage_, pokemonId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "playerLatitude",
        .dataTypeSpecific.className = NULL,
        .number = FortRecallPokemonMessage_FieldNumber_PlayerLatitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(FortRecallPokemonMessage__storage_, playerLatitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "playerLongitude",
        .dataTypeSpecific.className = NULL,
        .number = FortRecallPokemonMessage_FieldNumber_PlayerLongitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(FortRecallPokemonMessage__storage_, playerLongitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FortRecallPokemonMessage class]
                                     rootClass:[FortRecallPokemonMessageRoot class]
                                          file:FortRecallPokemonMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FortRecallPokemonMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
