// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/GetInventoryMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetInventoryMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetInventoryMessageRoot

@implementation GetInventoryMessageRoot

@end

#pragma mark - GetInventoryMessageRoot_FileDescriptor

static GPBFileDescriptor *GetInventoryMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetInventoryMessage

@implementation GetInventoryMessage

@dynamic lastTimestampMs;
@dynamic itemBeenSeen;

typedef struct GetInventoryMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t itemBeenSeen;
  int64_t lastTimestampMs;
} GetInventoryMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "lastTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = GetInventoryMessage_FieldNumber_LastTimestampMs,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetInventoryMessage__storage_, lastTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "itemBeenSeen",
        .dataTypeSpecific.className = NULL,
        .number = GetInventoryMessage_FieldNumber_ItemBeenSeen,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetInventoryMessage__storage_, itemBeenSeen),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetInventoryMessage class]
                                     rootClass:[GetInventoryMessageRoot class]
                                          file:GetInventoryMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetInventoryMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
