// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/MarkTutorialCompleteMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MarkTutorialCompleteMessage.pbobjc.h"
 #import "TutorialState.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MarkTutorialCompleteMessageRoot

@implementation MarkTutorialCompleteMessageRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[TutorialStateRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - MarkTutorialCompleteMessageRoot_FileDescriptor

static GPBFileDescriptor *MarkTutorialCompleteMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MarkTutorialCompleteMessage

@implementation MarkTutorialCompleteMessage

@dynamic tutorialsCompletedArray, tutorialsCompletedArray_Count;
@dynamic sendMarketingEmails;
@dynamic sendPushNotifications;

typedef struct MarkTutorialCompleteMessage__storage_ {
  uint32_t _has_storage_[1];
  GPBEnumArray *tutorialsCompletedArray;
} MarkTutorialCompleteMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "tutorialsCompletedArray",
        .dataTypeSpecific.enumDescFunc = TutorialState_EnumDescriptor,
        .number = MarkTutorialCompleteMessage_FieldNumber_TutorialsCompletedArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MarkTutorialCompleteMessage__storage_, tutorialsCompletedArray),
        .flags = GPBFieldRepeated | GPBFieldPacked | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "sendMarketingEmails",
        .dataTypeSpecific.className = NULL,
        .number = MarkTutorialCompleteMessage_FieldNumber_SendMarketingEmails,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "sendPushNotifications",
        .dataTypeSpecific.className = NULL,
        .number = MarkTutorialCompleteMessage_FieldNumber_SendPushNotifications,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MarkTutorialCompleteMessage class]
                                     rootClass:[MarkTutorialCompleteMessageRoot class]
                                          file:MarkTutorialCompleteMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MarkTutorialCompleteMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
