// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - StartGymBattleMessageRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface StartGymBattleMessageRoot : GPBRootObject
@end

#pragma mark - StartGymBattleMessage

typedef GPB_ENUM(StartGymBattleMessage_FieldNumber) {
  StartGymBattleMessage_FieldNumber_GymId = 1,
  StartGymBattleMessage_FieldNumber_AttackingPokemonIdsArray = 2,
  StartGymBattleMessage_FieldNumber_DefendingPokemonId = 3,
  StartGymBattleMessage_FieldNumber_PlayerLatitude = 4,
  StartGymBattleMessage_FieldNumber_PlayerLongitude = 5,
};

@interface StartGymBattleMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *gymId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *attackingPokemonIdsArray;
/// The number of items in @c attackingPokemonIdsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger attackingPokemonIdsArray_Count;

/// needs to be fixed64, tested by Grover
@property(nonatomic, readwrite) uint64_t defendingPokemonId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
