// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UseItemCaptureMessage.pbobjc.h"
 #import "ItemId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UseItemCaptureMessageRoot

@implementation UseItemCaptureMessageRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ItemIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UseItemCaptureMessageRoot_FileDescriptor

static GPBFileDescriptor *UseItemCaptureMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UseItemCaptureMessage

@implementation UseItemCaptureMessage

@dynamic itemId;
@dynamic encounterId;
@dynamic spawnPointId;

typedef struct UseItemCaptureMessage__storage_ {
  uint32_t _has_storage_[1];
  ItemId itemId;
  NSString *spawnPointId;
  uint64_t encounterId;
} UseItemCaptureMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemId",
        .dataTypeSpecific.enumDescFunc = ItemId_EnumDescriptor,
        .number = UseItemCaptureMessage_FieldNumber_ItemId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UseItemCaptureMessage__storage_, itemId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = UseItemCaptureMessage_FieldNumber_EncounterId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UseItemCaptureMessage__storage_, encounterId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "spawnPointId",
        .dataTypeSpecific.className = NULL,
        .number = UseItemCaptureMessage_FieldNumber_SpawnPointId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UseItemCaptureMessage__storage_, spawnPointId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UseItemCaptureMessage class]
                                     rootClass:[UseItemCaptureMessageRoot class]
                                          file:UseItemCaptureMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UseItemCaptureMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UseItemCaptureMessage_ItemId_RawValue(UseItemCaptureMessage *message) {
  GPBDescriptor *descriptor = [UseItemCaptureMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UseItemCaptureMessage_FieldNumber_ItemId];
  return GPBGetMessageInt32Field(message, field);
}

void SetUseItemCaptureMessage_ItemId_RawValue(UseItemCaptureMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [UseItemCaptureMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UseItemCaptureMessage_FieldNumber_ItemId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
