// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GlobalSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GlobalSettings.pbobjc.h"
 #import "FortSettings.pbobjc.h"
 #import "MapSettings.pbobjc.h"
 #import "LevelSettings.pbobjc.h"
 #import "InventorySettings.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GlobalSettingsRoot

@implementation GlobalSettingsRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[FortSettingsRoot extensionRegistry]];
    [registry addExtensions:[MapSettingsRoot extensionRegistry]];
    [registry addExtensions:[LevelSettingsRoot extensionRegistry]];
    [registry addExtensions:[InventorySettingsRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GlobalSettingsRoot_FileDescriptor

static GPBFileDescriptor *GlobalSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GlobalSettings

@implementation GlobalSettings

@dynamic hasFortSettings, fortSettings;
@dynamic hasMapSettings, mapSettings;
@dynamic hasLevelSettings, levelSettings;
@dynamic hasInventorySettings, inventorySettings;
@dynamic minimumClientVersion;

typedef struct GlobalSettings__storage_ {
  uint32_t _has_storage_[1];
  FortSettings *fortSettings;
  MapSettings *mapSettings;
  LevelSettings *levelSettings;
  InventorySettings *inventorySettings;
  NSString *minimumClientVersion;
} GlobalSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(FortSettings),
        .number = GlobalSettings_FieldNumber_FortSettings,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GlobalSettings__storage_, fortSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "mapSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(MapSettings),
        .number = GlobalSettings_FieldNumber_MapSettings,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GlobalSettings__storage_, mapSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "levelSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(LevelSettings),
        .number = GlobalSettings_FieldNumber_LevelSettings,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GlobalSettings__storage_, levelSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "inventorySettings",
        .dataTypeSpecific.className = GPBStringifySymbol(InventorySettings),
        .number = GlobalSettings_FieldNumber_InventorySettings,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GlobalSettings__storage_, inventorySettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "minimumClientVersion",
        .dataTypeSpecific.className = NULL,
        .number = GlobalSettings_FieldNumber_MinimumClientVersion,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GlobalSettings__storage_, minimumClientVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GlobalSettings class]
                                     rootClass:[GlobalSettingsRoot class]
                                          file:GlobalSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GlobalSettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
