// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/InventorySettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "InventorySettings.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - InventorySettingsRoot

@implementation InventorySettingsRoot

@end

#pragma mark - InventorySettingsRoot_FileDescriptor

static GPBFileDescriptor *InventorySettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - InventorySettings

@implementation InventorySettings

@dynamic maxPokemon;
@dynamic maxBagItems;
@dynamic basePokemon;
@dynamic baseBagItems;
@dynamic baseEggs;

typedef struct InventorySettings__storage_ {
  uint32_t _has_storage_[1];
  int32_t maxPokemon;
  int32_t maxBagItems;
  int32_t basePokemon;
  int32_t baseBagItems;
  int32_t baseEggs;
} InventorySettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "maxPokemon",
        .dataTypeSpecific.className = NULL,
        .number = InventorySettings_FieldNumber_MaxPokemon,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(InventorySettings__storage_, maxPokemon),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "maxBagItems",
        .dataTypeSpecific.className = NULL,
        .number = InventorySettings_FieldNumber_MaxBagItems,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(InventorySettings__storage_, maxBagItems),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "basePokemon",
        .dataTypeSpecific.className = NULL,
        .number = InventorySettings_FieldNumber_BasePokemon,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(InventorySettings__storage_, basePokemon),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "baseBagItems",
        .dataTypeSpecific.className = NULL,
        .number = InventorySettings_FieldNumber_BaseBagItems,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(InventorySettings__storage_, baseBagItems),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "baseEggs",
        .dataTypeSpecific.className = NULL,
        .number = InventorySettings_FieldNumber_BaseEggs,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(InventorySettings__storage_, baseEggs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[InventorySettings class]
                                     rootClass:[InventorySettingsRoot class]
                                          file:InventorySettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(InventorySettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
