// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/LevelUpRewardsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ItemAward;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum LevelUpRewardsResponse_Result

typedef GPB_ENUM(LevelUpRewardsResponse_Result) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LevelUpRewardsResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  LevelUpRewardsResponse_Result_Unset = 0,
  LevelUpRewardsResponse_Result_Success = 1,
  LevelUpRewardsResponse_Result_AwardedAlready = 2,
};

GPBEnumDescriptor *LevelUpRewardsResponse_Result_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LevelUpRewardsResponse_Result_IsValidValue(int32_t value);

#pragma mark - LevelUpRewardsResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface LevelUpRewardsResponseRoot : GPBRootObject
@end

#pragma mark - LevelUpRewardsResponse

typedef GPB_ENUM(LevelUpRewardsResponse_FieldNumber) {
  LevelUpRewardsResponse_FieldNumber_Result = 1,
  LevelUpRewardsResponse_FieldNumber_ItemsAwardedArray = 2,
  LevelUpRewardsResponse_FieldNumber_ItemsUnlockedArray = 4,
};

@interface LevelUpRewardsResponse : GPBMessage

@property(nonatomic, readwrite) LevelUpRewardsResponse_Result result;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ItemAward*> *itemsAwardedArray;
/// The number of items in @c itemsAwardedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger itemsAwardedArray_Count;

// |itemsUnlockedArray| contains |ItemId|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *itemsUnlockedArray;
/// The number of items in @c itemsUnlockedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger itemsUnlockedArray_Count;

@end

/// Fetches the raw value of a @c LevelUpRewardsResponse's @c result property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t LevelUpRewardsResponse_Result_RawValue(LevelUpRewardsResponse *message);
/// Sets the raw value of an @c LevelUpRewardsResponse's @c result property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetLevelUpRewardsResponse_Result_RawValue(LevelUpRewardsResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
