// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/SetAvatarResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PlayerData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SetAvatarResponse_Status

typedef GPB_ENUM(SetAvatarResponse_Status) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  SetAvatarResponse_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SetAvatarResponse_Status_Unset = 0,
  SetAvatarResponse_Status_Success = 1,
  SetAvatarResponse_Status_AvatarAlreadySet = 2,
  SetAvatarResponse_Status_Failure = 3,
};

GPBEnumDescriptor *SetAvatarResponse_Status_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL SetAvatarResponse_Status_IsValidValue(int32_t value);

#pragma mark - SetAvatarResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface SetAvatarResponseRoot : GPBRootObject
@end

#pragma mark - SetAvatarResponse

typedef GPB_ENUM(SetAvatarResponse_FieldNumber) {
  SetAvatarResponse_FieldNumber_Status = 1,
  SetAvatarResponse_FieldNumber_PlayerData = 2,
};

@interface SetAvatarResponse : GPBMessage

@property(nonatomic, readwrite) SetAvatarResponse_Status status;

@property(nonatomic, readwrite, strong, null_resettable) PlayerData *playerData;
/// Test to see if @c playerData has been set.
@property(nonatomic, readwrite) BOOL hasPlayerData;

@end

/// Fetches the raw value of a @c SetAvatarResponse's @c status property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SetAvatarResponse_Status_RawValue(SetAvatarResponse *message);
/// Sets the raw value of an @c SetAvatarResponse's @c status property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSetAvatarResponse_Status_RawValue(SetAvatarResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
