// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Envelopes/Unknown6Response.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Currency;
@class ItemData;
@class Unknown6Response_Unknown2;
@class Unknown6Response_Unknown2_StoreItem;
@class Unknown6Response_Unknown2_StoreItem_Tag;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Unknown6ResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface Unknown6ResponseRoot : GPBRootObject
@end

#pragma mark - Unknown6Response

typedef GPB_ENUM(Unknown6Response_FieldNumber) {
  Unknown6Response_FieldNumber_ResponseType = 1,
  Unknown6Response_FieldNumber_Unknown2 = 2,
};

@interface Unknown6Response : GPBMessage

/// Still don't know what 6 is, but 5 lists items available via IAPs. 
@property(nonatomic, readwrite) int32_t responseType;

/// Response data
@property(nonatomic, readwrite, strong, null_resettable) Unknown6Response_Unknown2 *unknown2;
/// Test to see if @c unknown2 has been set.
@property(nonatomic, readwrite) BOOL hasUnknown2;

@end

#pragma mark - Unknown6Response_Unknown2

typedef GPB_ENUM(Unknown6Response_Unknown2_FieldNumber) {
  Unknown6Response_Unknown2_FieldNumber_Unknown1 = 1,
  Unknown6Response_Unknown2_FieldNumber_ItemsArray = 2,
  Unknown6Response_Unknown2_FieldNumber_PlayerCurrenciesArray = 3,
  Unknown6Response_Unknown2_FieldNumber_Unknown4 = 4,
};

@interface Unknown6Response_Unknown2 : GPBMessage

/// Maybe status? It's always 1 (success), so it's probably that.
@property(nonatomic, readwrite) uint64_t unknown1;

/// Items to show in the shop
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Unknown6Response_Unknown2_StoreItem*> *itemsArray;
/// The number of items in @c itemsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

/// currencies that player has at the moment
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Currency*> *playerCurrenciesArray;
/// The number of items in @c playerCurrenciesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger playerCurrenciesArray_Count;

/// Some base64 encoded stuff...
@property(nonatomic, readwrite, copy, null_resettable) NSString *unknown4;

@end

#pragma mark - Unknown6Response_Unknown2_StoreItem

typedef GPB_ENUM(Unknown6Response_Unknown2_StoreItem_FieldNumber) {
  Unknown6Response_Unknown2_StoreItem_FieldNumber_ItemId = 1,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_IsIap = 2,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_CurrencyToBuy = 3,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_YieldsCurrency = 4,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_YieldsItem = 5,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_TagsArray = 6,
  Unknown6Response_Unknown2_StoreItem_FieldNumber_Unknown7 = 7,
};

@interface Unknown6Response_Unknown2_StoreItem : GPBMessage

/// Internal ID (probably for Google Play/App Store) example: "pgorelease.incenseordinary.1"
@property(nonatomic, readwrite, copy, null_resettable) NSString *itemId;

/// If true, this item is bought with real currency (USD, etc.) through the Play/App Store instead of Pokecoins
@property(nonatomic, readwrite) BOOL isIap;

/// This defines how much the item costs (with the exception of items that cost real money like Pokecoins, that's defined in the respective store)
@property(nonatomic, readwrite, strong, null_resettable) Currency *currencyToBuy;
/// Test to see if @c currencyToBuy has been set.
@property(nonatomic, readwrite) BOOL hasCurrencyToBuy;

/// When bought, this IAP will yield this much currency
@property(nonatomic, readwrite, strong, null_resettable) Currency *yieldsCurrency;
/// Test to see if @c yieldsCurrency has been set.
@property(nonatomic, readwrite) BOOL hasYieldsCurrency;

/// The item and count of such item that this IAP will yield
@property(nonatomic, readwrite, strong, null_resettable) ItemData *yieldsItem;
/// Test to see if @c yieldsItem has been set.
@property(nonatomic, readwrite) BOOL hasYieldsItem;

/// Stuff like SORT:12, CATEGORY:ITEMS
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Unknown6Response_Unknown2_StoreItem_Tag*> *tagsArray;
/// The number of items in @c tagsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

/// Possibly something to toggle visibility in the store/purchasibility?
@property(nonatomic, readwrite) int32_t unknown7;

@end

#pragma mark - Unknown6Response_Unknown2_StoreItem_Tag

typedef GPB_ENUM(Unknown6Response_Unknown2_StoreItem_Tag_FieldNumber) {
  Unknown6Response_Unknown2_StoreItem_Tag_FieldNumber_Key = 1,
  Unknown6Response_Unknown2_StoreItem_Tag_FieldNumber_Value = 2,
};

@interface Unknown6Response_Unknown2_StoreItem_Tag : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
